; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.11886.00 

	TITLE	C:\Users\PermaNulled\Desktop\Trainer_Engine\Trainer Engine\Trainer\CRC32.cpp
	.PPC
	.MODEL FLAT
PUBLIC	__C2_11886
PUBLIC	__C1_11886
;	COMDAT __C1_11886
.XBLD$W	SEGMENT
__C1_11886 DW	04331H
	DW	00H
	DW	00H
	DW	00H
	DW	010H
	DW	00H
	DW	02e6eH
	DW	04400H
;	COMDAT __C2_11886
.XBLD$W	SEGMENT
__C2_11886 DB	'C2', 00H, 00H, 00H, 00H, 00H, 00H, 00H, 010H, 00H, 00H, '.'
	DB	'nD', 00H
END
