; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.11886.00 

	TITLE	C:\Users\PermaNulled\Desktop\Trainer_Engine\Trainer Engine\Trainer\util.cpp
	.PPC
	.MODEL FLAT
PUBLIC	__C2_11886
PUBLIC	__C1_11886
PUBLIC	D3DPRIMITIVEVERTEXCOUNT
PUBLIC	D3DTESSPRIMITIVEVERTEXCOUNT
PUBLIC	?g_XMSinCoefficients0@@3UXMVECTORF32@@B		; g_XMSinCoefficients0
PUBLIC	?g_XMSinCoefficients1@@3UXMVECTORF32@@B		; g_XMSinCoefficients1
PUBLIC	?g_XMSinCoefficients2@@3UXMVECTORF32@@B		; g_XMSinCoefficients2
PUBLIC	?g_XMCosCoefficients0@@3UXMVECTORF32@@B		; g_XMCosCoefficients0
PUBLIC	?g_XMCosCoefficients1@@3UXMVECTORF32@@B		; g_XMCosCoefficients1
PUBLIC	?g_XMCosCoefficients2@@3UXMVECTORF32@@B		; g_XMCosCoefficients2
PUBLIC	?g_XMTanCoefficients0@@3UXMVECTORF32@@B		; g_XMTanCoefficients0
PUBLIC	?g_XMTanCoefficients1@@3UXMVECTORF32@@B		; g_XMTanCoefficients1
PUBLIC	?g_XMTanCoefficients2@@3UXMVECTORF32@@B		; g_XMTanCoefficients2
PUBLIC	?g_XMASinCoefficients0@@3UXMVECTORF32@@B	; g_XMASinCoefficients0
PUBLIC	?g_XMASinCoefficients1@@3UXMVECTORF32@@B	; g_XMASinCoefficients1
PUBLIC	?g_XMASinCoefficients2@@3UXMVECTORF32@@B	; g_XMASinCoefficients2
PUBLIC	?g_XMATanCoefficients0@@3UXMVECTORF32@@B	; g_XMATanCoefficients0
PUBLIC	?g_XMATanCoefficients1@@3UXMVECTORF32@@B	; g_XMATanCoefficients1
PUBLIC	?g_XMATanCoefficients2@@3UXMVECTORF32@@B	; g_XMATanCoefficients2
PUBLIC	?g_XMSinEstCoefficients@@3UXMVECTORF32@@B	; g_XMSinEstCoefficients
PUBLIC	?g_XMCosEstCoefficients@@3UXMVECTORF32@@B	; g_XMCosEstCoefficients
PUBLIC	?g_XMTanEstCoefficients@@3UXMVECTORF32@@B	; g_XMTanEstCoefficients
PUBLIC	?g_XMATanEstCoefficients@@3UXMVECTORF32@@B	; g_XMATanEstCoefficients
PUBLIC	?g_XMASinEstCoefficients@@3UXMVECTORF32@@B	; g_XMASinEstCoefficients
PUBLIC	?g_XMASinEstConstants@@3UXMVECTORF32@@B		; g_XMASinEstConstants
PUBLIC	?g_XMPiConstants0@@3UXMVECTORF32@@B		; g_XMPiConstants0
PUBLIC	?g_XMIdentityR0@@3UXMVECTORF32@@B		; g_XMIdentityR0
PUBLIC	?g_XMIdentityR1@@3UXMVECTORF32@@B		; g_XMIdentityR1
PUBLIC	?g_XMIdentityR2@@3UXMVECTORF32@@B		; g_XMIdentityR2
PUBLIC	?g_XMIdentityR3@@3UXMVECTORF32@@B		; g_XMIdentityR3
PUBLIC	?g_XMNegIdentityR0@@3UXMVECTORF32@@B		; g_XMNegIdentityR0
PUBLIC	?g_XMNegIdentityR1@@3UXMVECTORF32@@B		; g_XMNegIdentityR1
PUBLIC	?g_XMNegIdentityR2@@3UXMVECTORF32@@B		; g_XMNegIdentityR2
PUBLIC	?g_XMNegIdentityR3@@3UXMVECTORF32@@B		; g_XMNegIdentityR3
PUBLIC	?g_XMNegativeZero@@3UXMVECTORI32@@B		; g_XMNegativeZero
PUBLIC	?g_XMNegate3@@3UXMVECTORI32@@B			; g_XMNegate3
PUBLIC	?g_XMMask3@@3UXMVECTORI32@@B			; g_XMMask3
PUBLIC	?g_XMMaskX@@3UXMVECTORI32@@B			; g_XMMaskX
PUBLIC	?g_XMMaskY@@3UXMVECTORI32@@B			; g_XMMaskY
PUBLIC	?g_XMMaskZ@@3UXMVECTORI32@@B			; g_XMMaskZ
PUBLIC	?g_XMMaskW@@3UXMVECTORI32@@B			; g_XMMaskW
PUBLIC	?g_XMOne@@3UXMVECTORF32@@B			; g_XMOne
PUBLIC	?g_XMOne3@@3UXMVECTORF32@@B			; g_XMOne3
PUBLIC	?g_XMZero@@3UXMVECTORF32@@B			; g_XMZero
PUBLIC	?g_XMNegativeOne@@3UXMVECTORF32@@B		; g_XMNegativeOne
PUBLIC	?g_XMOneHalf@@3UXMVECTORF32@@B			; g_XMOneHalf
PUBLIC	?g_XMNegativeOneHalf@@3UXMVECTORF32@@B		; g_XMNegativeOneHalf
PUBLIC	?g_XMNegativeTwoPi@@3UXMVECTORF32@@B		; g_XMNegativeTwoPi
PUBLIC	?g_XMNegativePi@@3UXMVECTORF32@@B		; g_XMNegativePi
PUBLIC	?g_XMHalfPi@@3UXMVECTORF32@@B			; g_XMHalfPi
PUBLIC	?g_XMPi@@3UXMVECTORF32@@B			; g_XMPi
PUBLIC	?g_XMReciprocalPi@@3UXMVECTORF32@@B		; g_XMReciprocalPi
PUBLIC	?g_XMTwoPi@@3UXMVECTORF32@@B			; g_XMTwoPi
PUBLIC	?g_XMReciprocalTwoPi@@3UXMVECTORF32@@B		; g_XMReciprocalTwoPi
PUBLIC	?g_XMEpsilon@@3UXMVECTORF32@@B			; g_XMEpsilon
PUBLIC	?g_XMInfinity@@3UXMVECTORI32@@B			; g_XMInfinity
PUBLIC	?g_XMQNaN@@3UXMVECTORI32@@B			; g_XMQNaN
PUBLIC	?g_XMQNaNTest@@3UXMVECTORI32@@B			; g_XMQNaNTest
PUBLIC	?g_XMAbsMask@@3UXMVECTORI32@@B			; g_XMAbsMask
PUBLIC	?g_XMFltMin@@3UXMVECTORI32@@B			; g_XMFltMin
PUBLIC	?g_XMFltMax@@3UXMVECTORI32@@B			; g_XMFltMax
PUBLIC	?g_XMNegOneMask@@3UXMVECTORI32@@B		; g_XMNegOneMask
PUBLIC	?g_XMMaskA8R8G8B8@@3UXMVECTORI32@@B		; g_XMMaskA8R8G8B8
PUBLIC	?g_XMFlipA8R8G8B8@@3UXMVECTORI32@@B		; g_XMFlipA8R8G8B8
PUBLIC	?g_XMFixAA8R8G8B8@@3UXMVECTORF32@@B		; g_XMFixAA8R8G8B8
PUBLIC	?g_XMNormalizeA8R8G8B8@@3UXMVECTORF32@@B	; g_XMNormalizeA8R8G8B8
PUBLIC	?g_XMMaskA2B10G10R10@@3UXMVECTORI32@@B		; g_XMMaskA2B10G10R10
PUBLIC	?g_XMFlipA2B10G10R10@@3UXMVECTORI32@@B		; g_XMFlipA2B10G10R10
PUBLIC	?g_XMFixAA2B10G10R10@@3UXMVECTORF32@@B		; g_XMFixAA2B10G10R10
PUBLIC	?g_XMNormalizeA2B10G10R10@@3UXMVECTORF32@@B	; g_XMNormalizeA2B10G10R10
PUBLIC	?g_XMMaskX16Y16@@3UXMVECTORI32@@B		; g_XMMaskX16Y16
PUBLIC	?g_XMFlipX16Y16@@3UXMVECTORI32@@B		; g_XMFlipX16Y16
PUBLIC	?g_XMFixX16Y16@@3UXMVECTORF32@@B		; g_XMFixX16Y16
PUBLIC	?g_XMNormalizeX16Y16@@3UXMVECTORF32@@B		; g_XMNormalizeX16Y16
PUBLIC	?g_XMMaskX16Y16Z16W16@@3UXMVECTORI32@@B		; g_XMMaskX16Y16Z16W16
PUBLIC	?g_XMFlipX16Y16Z16W16@@3UXMVECTORI32@@B		; g_XMFlipX16Y16Z16W16
PUBLIC	?g_XMFixX16Y16Z16W16@@3UXMVECTORF32@@B		; g_XMFixX16Y16Z16W16
PUBLIC	?g_XMNormalizeX16Y16Z16W16@@3UXMVECTORF32@@B	; g_XMNormalizeX16Y16Z16W16
PUBLIC	?g_XMNoFraction@@3UXMVECTORF32@@B		; g_XMNoFraction
PUBLIC	?g_XMMaskByte@@3UXMVECTORI32@@B			; g_XMMaskByte
PUBLIC	?g_XMNegateX@@3UXMVECTORF32@@B			; g_XMNegateX
PUBLIC	?g_XMNegateY@@3UXMVECTORF32@@B			; g_XMNegateY
PUBLIC	?g_XMNegateZ@@3UXMVECTORF32@@B			; g_XMNegateZ
PUBLIC	?g_XMNegateW@@3UXMVECTORF32@@B			; g_XMNegateW
PUBLIC	?g_XMSelect0101@@3UXMVECTORI32@@B		; g_XMSelect0101
PUBLIC	?g_XMSelect1010@@3UXMVECTORI32@@B		; g_XMSelect1010
PUBLIC	?g_XMOneHalfMinusEpsilon@@3UXMVECTORI32@@B	; g_XMOneHalfMinusEpsilon
PUBLIC	?g_XMSelect1000@@3UXMVECTORI32@@B		; g_XMSelect1000
PUBLIC	?g_XMSelect1100@@3UXMVECTORI32@@B		; g_XMSelect1100
PUBLIC	?g_XMSelect1110@@3UXMVECTORI32@@B		; g_XMSelect1110
PUBLIC	?g_XMSwizzleXYXY@@3UXMVECTORI32@@B		; g_XMSwizzleXYXY
PUBLIC	?g_XMSwizzleXYZX@@3UXMVECTORI32@@B		; g_XMSwizzleXYZX
PUBLIC	?g_XMSwizzleYXZW@@3UXMVECTORI32@@B		; g_XMSwizzleYXZW
PUBLIC	?g_XMSwizzleYZXW@@3UXMVECTORI32@@B		; g_XMSwizzleYZXW
PUBLIC	?g_XMSwizzleZXYW@@3UXMVECTORI32@@B		; g_XMSwizzleZXYW
PUBLIC	?g_XMPermute0X0Y1X1Y@@3UXMVECTORI32@@B		; g_XMPermute0X0Y1X1Y
PUBLIC	?g_XMPermute0Z0W1Z1W@@3UXMVECTORI32@@B		; g_XMPermute0Z0W1Z1W
PUBLIC	?g_XMFixupY16@@3UXMVECTORF32@@B			; g_XMFixupY16
PUBLIC	?g_XMFixupY16W16@@3UXMVECTORF32@@B		; g_XMFixupY16W16
PUBLIC	?g_XMFlipY@@3UXMVECTORI32@@B			; g_XMFlipY
PUBLIC	?g_XMFlipZ@@3UXMVECTORI32@@B			; g_XMFlipZ
PUBLIC	?g_XMFlipW@@3UXMVECTORI32@@B			; g_XMFlipW
PUBLIC	?g_XMFlipYZ@@3UXMVECTORI32@@B			; g_XMFlipYZ
PUBLIC	?g_XMFlipZW@@3UXMVECTORI32@@B			; g_XMFlipZW
PUBLIC	?g_XMFlipYW@@3UXMVECTORI32@@B			; g_XMFlipYW
PUBLIC	?g_XMMaskHenD3@@3UXMVECTORI32@@B		; g_XMMaskHenD3
PUBLIC	?g_XMMaskDHen3@@3UXMVECTORI32@@B		; g_XMMaskDHen3
PUBLIC	?g_XMAddUHenD3@@3UXMVECTORF32@@B		; g_XMAddUHenD3
PUBLIC	?g_XMAddHenD3@@3UXMVECTORF32@@B			; g_XMAddHenD3
PUBLIC	?g_XMAddDHen3@@3UXMVECTORF32@@B			; g_XMAddDHen3
PUBLIC	?g_XMMulHenD3@@3UXMVECTORF32@@B			; g_XMMulHenD3
PUBLIC	?g_XMMulDHen3@@3UXMVECTORF32@@B			; g_XMMulDHen3
PUBLIC	?g_XMXorHenD3@@3UXMVECTORI32@@B			; g_XMXorHenD3
PUBLIC	?g_XMXorDHen3@@3UXMVECTORI32@@B			; g_XMXorDHen3
PUBLIC	?g_XMMaskIco4@@3UXMVECTORI32@@B			; g_XMMaskIco4
PUBLIC	?g_XMXorXIco4@@3UXMVECTORI32@@B			; g_XMXorXIco4
PUBLIC	?g_XMXorIco4@@3UXMVECTORI32@@B			; g_XMXorIco4
PUBLIC	?g_XMAddXIco4@@3UXMVECTORF32@@B			; g_XMAddXIco4
PUBLIC	?g_XMAddUIco4@@3UXMVECTORF32@@B			; g_XMAddUIco4
PUBLIC	?g_XMAddIco4@@3UXMVECTORF32@@B			; g_XMAddIco4
PUBLIC	?g_XMMulIco4@@3UXMVECTORF32@@B			; g_XMMulIco4
PUBLIC	?g_XMMaskDec4@@3UXMVECTORI32@@B			; g_XMMaskDec4
PUBLIC	?g_XMXorDec4@@3UXMVECTORI32@@B			; g_XMXorDec4
PUBLIC	?g_XMAddUDec4@@3UXMVECTORF32@@B			; g_XMAddUDec4
PUBLIC	?g_XMAddDec4@@3UXMVECTORF32@@B			; g_XMAddDec4
PUBLIC	?g_XMMulDec4@@3UXMVECTORF32@@B			; g_XMMulDec4
PUBLIC	?g_XMMaskByte4@@3UXMVECTORI32@@B		; g_XMMaskByte4
PUBLIC	?g_XMXorByte4@@3UXMVECTORI32@@B			; g_XMXorByte4
PUBLIC	?g_XMAddByte4@@3UXMVECTORF32@@B			; g_XMAddByte4
PUBLIC	?g_XMFixUnsigned@@3UXMVECTORF32@@B		; g_XMFixUnsigned
PUBLIC	?g_XMMaxInt@@3UXMVECTORF32@@B			; g_XMMaxInt
PUBLIC	?g_XMMaxUInt@@3UXMVECTORF32@@B			; g_XMMaxUInt
PUBLIC	?g_XMUnsignedFix@@3UXMVECTORF32@@B		; g_XMUnsignedFix
PUBLIC	?has_denorm@_Num_base@std@@2W4float_denorm_style@2@B ; std::_Num_base::has_denorm
PUBLIC	?has_denorm_loss@_Num_base@std@@2_NB		; std::_Num_base::has_denorm_loss
PUBLIC	?has_infinity@_Num_base@std@@2_NB		; std::_Num_base::has_infinity
PUBLIC	?has_quiet_NaN@_Num_base@std@@2_NB		; std::_Num_base::has_quiet_NaN
PUBLIC	?has_signaling_NaN@_Num_base@std@@2_NB		; std::_Num_base::has_signaling_NaN
PUBLIC	?is_bounded@_Num_base@std@@2_NB			; std::_Num_base::is_bounded
PUBLIC	?is_exact@_Num_base@std@@2_NB			; std::_Num_base::is_exact
PUBLIC	?is_iec559@_Num_base@std@@2_NB			; std::_Num_base::is_iec559
PUBLIC	?is_integer@_Num_base@std@@2_NB			; std::_Num_base::is_integer
PUBLIC	?is_modulo@_Num_base@std@@2_NB			; std::_Num_base::is_modulo
PUBLIC	?is_signed@_Num_base@std@@2_NB			; std::_Num_base::is_signed
PUBLIC	?is_specialized@_Num_base@std@@2_NB		; std::_Num_base::is_specialized
PUBLIC	?tinyness_before@_Num_base@std@@2_NB		; std::_Num_base::tinyness_before
PUBLIC	?traps@_Num_base@std@@2_NB			; std::_Num_base::traps
PUBLIC	?round_style@_Num_base@std@@2W4float_round_style@2@B ; std::_Num_base::round_style
PUBLIC	?digits@_Num_base@std@@2HB			; std::_Num_base::digits
PUBLIC	?digits10@_Num_base@std@@2HB			; std::_Num_base::digits10
PUBLIC	?max_digits10@_Num_base@std@@2HB		; std::_Num_base::max_digits10
PUBLIC	?max_exponent@_Num_base@std@@2HB		; std::_Num_base::max_exponent
PUBLIC	?max_exponent10@_Num_base@std@@2HB		; std::_Num_base::max_exponent10
PUBLIC	?min_exponent@_Num_base@std@@2HB		; std::_Num_base::min_exponent
PUBLIC	?min_exponent10@_Num_base@std@@2HB		; std::_Num_base::min_exponent10
PUBLIC	?radix@_Num_base@std@@2HB			; std::_Num_base::radix
PUBLIC	?is_bounded@_Num_int_base@std@@2_NB		; std::_Num_int_base::is_bounded
PUBLIC	?is_exact@_Num_int_base@std@@2_NB		; std::_Num_int_base::is_exact
PUBLIC	?is_integer@_Num_int_base@std@@2_NB		; std::_Num_int_base::is_integer
PUBLIC	?is_modulo@_Num_int_base@std@@2_NB		; std::_Num_int_base::is_modulo
PUBLIC	?is_specialized@_Num_int_base@std@@2_NB		; std::_Num_int_base::is_specialized
PUBLIC	?radix@_Num_int_base@std@@2HB			; std::_Num_int_base::radix
PUBLIC	?has_denorm@_Num_float_base@std@@2W4float_denorm_style@2@B ; std::_Num_float_base::has_denorm
PUBLIC	?has_denorm_loss@_Num_float_base@std@@2_NB	; std::_Num_float_base::has_denorm_loss
PUBLIC	?has_infinity@_Num_float_base@std@@2_NB		; std::_Num_float_base::has_infinity
PUBLIC	?has_quiet_NaN@_Num_float_base@std@@2_NB	; std::_Num_float_base::has_quiet_NaN
PUBLIC	?has_signaling_NaN@_Num_float_base@std@@2_NB	; std::_Num_float_base::has_signaling_NaN
PUBLIC	?is_bounded@_Num_float_base@std@@2_NB		; std::_Num_float_base::is_bounded
PUBLIC	?is_exact@_Num_float_base@std@@2_NB		; std::_Num_float_base::is_exact
PUBLIC	?is_iec559@_Num_float_base@std@@2_NB		; std::_Num_float_base::is_iec559
PUBLIC	?is_integer@_Num_float_base@std@@2_NB		; std::_Num_float_base::is_integer
PUBLIC	?is_modulo@_Num_float_base@std@@2_NB		; std::_Num_float_base::is_modulo
PUBLIC	?is_signed@_Num_float_base@std@@2_NB		; std::_Num_float_base::is_signed
PUBLIC	?is_specialized@_Num_float_base@std@@2_NB	; std::_Num_float_base::is_specialized
PUBLIC	?tinyness_before@_Num_float_base@std@@2_NB	; std::_Num_float_base::tinyness_before
PUBLIC	?traps@_Num_float_base@std@@2_NB		; std::_Num_float_base::traps
PUBLIC	?round_style@_Num_float_base@std@@2W4float_round_style@2@B ; std::_Num_float_base::round_style
PUBLIC	?radix@_Num_float_base@std@@2HB			; std::_Num_float_base::radix
PUBLIC	?is_signed@?$numeric_limits@D@std@@2_NB		; std::numeric_limits<char>::is_signed
PUBLIC	?digits@?$numeric_limits@D@std@@2HB		; std::numeric_limits<char>::digits
PUBLIC	?digits10@?$numeric_limits@D@std@@2HB		; std::numeric_limits<char>::digits10
PUBLIC	?max_digits10@?$numeric_limits@D@std@@2HB	; std::numeric_limits<char>::max_digits10
PUBLIC	?is_signed@?$numeric_limits@_W@std@@2_NB	; std::numeric_limits<wchar_t>::is_signed
PUBLIC	?digits@?$numeric_limits@_W@std@@2HB		; std::numeric_limits<wchar_t>::digits
PUBLIC	?digits10@?$numeric_limits@_W@std@@2HB		; std::numeric_limits<wchar_t>::digits10
PUBLIC	?max_digits10@?$numeric_limits@_W@std@@2HB	; std::numeric_limits<wchar_t>::max_digits10
PUBLIC	?is_modulo@?$numeric_limits@_N@std@@2_NB	; std::numeric_limits<bool>::is_modulo
PUBLIC	?is_signed@?$numeric_limits@_N@std@@2_NB	; std::numeric_limits<bool>::is_signed
PUBLIC	?digits@?$numeric_limits@_N@std@@2HB		; std::numeric_limits<bool>::digits
PUBLIC	?digits10@?$numeric_limits@_N@std@@2HB		; std::numeric_limits<bool>::digits10
PUBLIC	?max_digits10@?$numeric_limits@_N@std@@2HB	; std::numeric_limits<bool>::max_digits10
PUBLIC	?is_signed@?$numeric_limits@C@std@@2_NB		; std::numeric_limits<signed char>::is_signed
PUBLIC	?digits@?$numeric_limits@C@std@@2HB		; std::numeric_limits<signed char>::digits
PUBLIC	?digits10@?$numeric_limits@C@std@@2HB		; std::numeric_limits<signed char>::digits10
PUBLIC	?max_digits10@?$numeric_limits@C@std@@2HB	; std::numeric_limits<signed char>::max_digits10
PUBLIC	?is_signed@?$numeric_limits@E@std@@2_NB		; std::numeric_limits<unsigned char>::is_signed
PUBLIC	?digits@?$numeric_limits@E@std@@2HB		; std::numeric_limits<unsigned char>::digits
PUBLIC	?digits10@?$numeric_limits@E@std@@2HB		; std::numeric_limits<unsigned char>::digits10
PUBLIC	?max_digits10@?$numeric_limits@E@std@@2HB	; std::numeric_limits<unsigned char>::max_digits10
PUBLIC	?is_signed@?$numeric_limits@F@std@@2_NB		; std::numeric_limits<short>::is_signed
PUBLIC	?digits@?$numeric_limits@F@std@@2HB		; std::numeric_limits<short>::digits
PUBLIC	?digits10@?$numeric_limits@F@std@@2HB		; std::numeric_limits<short>::digits10
PUBLIC	?max_digits10@?$numeric_limits@F@std@@2HB	; std::numeric_limits<short>::max_digits10
PUBLIC	?is_signed@?$numeric_limits@G@std@@2_NB		; std::numeric_limits<unsigned short>::is_signed
PUBLIC	?digits@?$numeric_limits@G@std@@2HB		; std::numeric_limits<unsigned short>::digits
PUBLIC	?digits10@?$numeric_limits@G@std@@2HB		; std::numeric_limits<unsigned short>::digits10
PUBLIC	?max_digits10@?$numeric_limits@G@std@@2HB	; std::numeric_limits<unsigned short>::max_digits10
PUBLIC	?is_signed@?$numeric_limits@H@std@@2_NB		; std::numeric_limits<int>::is_signed
PUBLIC	?digits@?$numeric_limits@H@std@@2HB		; std::numeric_limits<int>::digits
PUBLIC	?digits10@?$numeric_limits@H@std@@2HB		; std::numeric_limits<int>::digits10
PUBLIC	?max_digits10@?$numeric_limits@H@std@@2HB	; std::numeric_limits<int>::max_digits10
PUBLIC	?is_signed@?$numeric_limits@I@std@@2_NB		; std::numeric_limits<unsigned int>::is_signed
PUBLIC	?digits@?$numeric_limits@I@std@@2HB		; std::numeric_limits<unsigned int>::digits
PUBLIC	?digits10@?$numeric_limits@I@std@@2HB		; std::numeric_limits<unsigned int>::digits10
PUBLIC	?max_digits10@?$numeric_limits@I@std@@2HB	; std::numeric_limits<unsigned int>::max_digits10
PUBLIC	?is_signed@?$numeric_limits@J@std@@2_NB		; std::numeric_limits<long>::is_signed
PUBLIC	?digits@?$numeric_limits@J@std@@2HB		; std::numeric_limits<long>::digits
PUBLIC	?digits10@?$numeric_limits@J@std@@2HB		; std::numeric_limits<long>::digits10
PUBLIC	?max_digits10@?$numeric_limits@J@std@@2HB	; std::numeric_limits<long>::max_digits10
PUBLIC	?is_signed@?$numeric_limits@K@std@@2_NB		; std::numeric_limits<unsigned long>::is_signed
PUBLIC	?digits@?$numeric_limits@K@std@@2HB		; std::numeric_limits<unsigned long>::digits
PUBLIC	?digits10@?$numeric_limits@K@std@@2HB		; std::numeric_limits<unsigned long>::digits10
PUBLIC	?max_digits10@?$numeric_limits@K@std@@2HB	; std::numeric_limits<unsigned long>::max_digits10
PUBLIC	?is_signed@?$numeric_limits@_J@std@@2_NB	; std::numeric_limits<__int64>::is_signed
PUBLIC	?digits@?$numeric_limits@_J@std@@2HB		; std::numeric_limits<__int64>::digits
PUBLIC	?digits10@?$numeric_limits@_J@std@@2HB		; std::numeric_limits<__int64>::digits10
PUBLIC	?max_digits10@?$numeric_limits@_J@std@@2HB	; std::numeric_limits<__int64>::max_digits10
PUBLIC	?is_signed@?$numeric_limits@_K@std@@2_NB	; std::numeric_limits<unsigned __int64>::is_signed
PUBLIC	?digits@?$numeric_limits@_K@std@@2HB		; std::numeric_limits<unsigned __int64>::digits
PUBLIC	?digits10@?$numeric_limits@_K@std@@2HB		; std::numeric_limits<unsigned __int64>::digits10
PUBLIC	?max_digits10@?$numeric_limits@_K@std@@2HB	; std::numeric_limits<unsigned __int64>::max_digits10
PUBLIC	?digits@?$numeric_limits@M@std@@2HB		; std::numeric_limits<float>::digits
PUBLIC	?digits10@?$numeric_limits@M@std@@2HB		; std::numeric_limits<float>::digits10
PUBLIC	?max_digits10@?$numeric_limits@M@std@@2HB	; std::numeric_limits<float>::max_digits10
PUBLIC	?max_exponent@?$numeric_limits@M@std@@2HB	; std::numeric_limits<float>::max_exponent
PUBLIC	?max_exponent10@?$numeric_limits@M@std@@2HB	; std::numeric_limits<float>::max_exponent10
PUBLIC	?min_exponent@?$numeric_limits@M@std@@2HB	; std::numeric_limits<float>::min_exponent
PUBLIC	?min_exponent10@?$numeric_limits@M@std@@2HB	; std::numeric_limits<float>::min_exponent10
PUBLIC	?digits@?$numeric_limits@N@std@@2HB		; std::numeric_limits<double>::digits
PUBLIC	?digits10@?$numeric_limits@N@std@@2HB		; std::numeric_limits<double>::digits10
PUBLIC	?max_digits10@?$numeric_limits@N@std@@2HB	; std::numeric_limits<double>::max_digits10
PUBLIC	?max_exponent@?$numeric_limits@N@std@@2HB	; std::numeric_limits<double>::max_exponent
PUBLIC	?max_exponent10@?$numeric_limits@N@std@@2HB	; std::numeric_limits<double>::max_exponent10
PUBLIC	?min_exponent@?$numeric_limits@N@std@@2HB	; std::numeric_limits<double>::min_exponent
PUBLIC	?min_exponent10@?$numeric_limits@N@std@@2HB	; std::numeric_limits<double>::min_exponent10
PUBLIC	?digits@?$numeric_limits@O@std@@2HB		; std::numeric_limits<long double>::digits
PUBLIC	?digits10@?$numeric_limits@O@std@@2HB		; std::numeric_limits<long double>::digits10
PUBLIC	?max_digits10@?$numeric_limits@O@std@@2HB	; std::numeric_limits<long double>::max_digits10
PUBLIC	?max_exponent@?$numeric_limits@O@std@@2HB	; std::numeric_limits<long double>::max_exponent
PUBLIC	?max_exponent10@?$numeric_limits@O@std@@2HB	; std::numeric_limits<long double>::max_exponent10
PUBLIC	?min_exponent@?$numeric_limits@O@std@@2HB	; std::numeric_limits<long double>::min_exponent
PUBLIC	?min_exponent10@?$numeric_limits@O@std@@2HB	; std::numeric_limits<long double>::min_exponent10
PUBLIC	?value@?$integral_constant@_N$0A@@tr1@std@@2_NB	; std::tr1::integral_constant<bool,0>::value
PUBLIC	?value@?$integral_constant@_N$00@tr1@std@@2_NB	; std::tr1::integral_constant<bool,1>::value
PUBLIC	?value@?$integral_constant@I$0A@@tr1@std@@2IB	; std::tr1::integral_constant<unsigned int,0>::value
PUBLIC	?_Rank@?$_Arithmetic_traits@_N@std@@2HB		; std::_Arithmetic_traits<bool>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@D@std@@2HB		; std::_Arithmetic_traits<char>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@C@std@@2HB		; std::_Arithmetic_traits<signed char>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@E@std@@2HB		; std::_Arithmetic_traits<unsigned char>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@F@std@@2HB		; std::_Arithmetic_traits<short>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@G@std@@2HB		; std::_Arithmetic_traits<unsigned short>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@H@std@@2HB		; std::_Arithmetic_traits<int>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@I@std@@2HB		; std::_Arithmetic_traits<unsigned int>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@J@std@@2HB		; std::_Arithmetic_traits<long>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@K@std@@2HB		; std::_Arithmetic_traits<unsigned long>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@_J@std@@2HB		; std::_Arithmetic_traits<__int64>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@_K@std@@2HB		; std::_Arithmetic_traits<unsigned __int64>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@M@std@@2HB		; std::_Arithmetic_traits<float>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@N@std@@2HB		; std::_Arithmetic_traits<double>::_Rank
PUBLIC	?_Rank@?$_Arithmetic_traits@O@std@@2HB		; std::_Arithmetic_traits<long double>::_Rank
PUBLIC	?collate@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::collate
PUBLIC	?ctype@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::ctype
PUBLIC	?monetary@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::monetary
PUBLIC	?numeric@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::numeric
PUBLIC	?time@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::time
PUBLIC	?messages@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::messages
PUBLIC	?all@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::all
PUBLIC	?none@?$_Locbase@H@std@@2HB			; std::_Locbase<int>::none
PUBLIC	?table_size@?$ctype@D@std@@2IB			; std::ctype<char>::table_size
PUBLIC	?skipws@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::skipws
PUBLIC	?unitbuf@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::unitbuf
PUBLIC	?uppercase@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::uppercase
PUBLIC	?showbase@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::showbase
PUBLIC	?showpoint@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::showpoint
PUBLIC	?showpos@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::showpos
PUBLIC	?left@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::left
PUBLIC	?right@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::right
PUBLIC	?internal@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::internal
PUBLIC	?dec@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::dec
PUBLIC	?oct@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::oct
PUBLIC	?hex@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::hex
PUBLIC	?scientific@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::scientific
PUBLIC	?fixed@?$_Iosb@H@std@@2W4_Fmtflags@12@B		; std::_Iosb<int>::fixed
PUBLIC	?hexfloat@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::hexfloat
PUBLIC	?boolalpha@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::boolalpha
PUBLIC	?_Stdio@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::_Stdio
PUBLIC	?adjustfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::adjustfield
PUBLIC	?basefield@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::basefield
PUBLIC	?floatfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B	; std::_Iosb<int>::floatfield
PUBLIC	?goodbit@?$_Iosb@H@std@@2W4_Iostate@12@B	; std::_Iosb<int>::goodbit
PUBLIC	?eofbit@?$_Iosb@H@std@@2W4_Iostate@12@B		; std::_Iosb<int>::eofbit
PUBLIC	?failbit@?$_Iosb@H@std@@2W4_Iostate@12@B	; std::_Iosb<int>::failbit
PUBLIC	?badbit@?$_Iosb@H@std@@2W4_Iostate@12@B		; std::_Iosb<int>::badbit
PUBLIC	?_Hardfail@?$_Iosb@H@std@@2W4_Iostate@12@B	; std::_Iosb<int>::_Hardfail
PUBLIC	?in@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::in
PUBLIC	?out@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::out
PUBLIC	?ate@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::ate
PUBLIC	?app@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::app
PUBLIC	?trunc@?$_Iosb@H@std@@2W4_Openmode@12@B		; std::_Iosb<int>::trunc
PUBLIC	?_Nocreate@?$_Iosb@H@std@@2W4_Openmode@12@B	; std::_Iosb<int>::_Nocreate
PUBLIC	?_Noreplace@?$_Iosb@H@std@@2W4_Openmode@12@B	; std::_Iosb<int>::_Noreplace
PUBLIC	?binary@?$_Iosb@H@std@@2W4_Openmode@12@B	; std::_Iosb<int>::binary
PUBLIC	?beg@?$_Iosb@H@std@@2W4_Seekdir@12@B		; std::_Iosb<int>::beg
PUBLIC	?cur@?$_Iosb@H@std@@2W4_Seekdir@12@B		; std::_Iosb<int>::cur
PUBLIC	?end@?$_Iosb@H@std@@2W4_Seekdir@12@B		; std::_Iosb<int>::end
;	COMDAT ?end@?$_Iosb@H@std@@2W4_Seekdir@12@B
.rdata	SEGMENT
?end@?$_Iosb@H@std@@2W4_Seekdir@12@B DD 02H		; std::_Iosb<int>::end
;	COMDAT ?cur@?$_Iosb@H@std@@2W4_Seekdir@12@B
.rdata	SEGMENT
?cur@?$_Iosb@H@std@@2W4_Seekdir@12@B DD 01H		; std::_Iosb<int>::cur
;	COMDAT ?beg@?$_Iosb@H@std@@2W4_Seekdir@12@B
.rdata	SEGMENT
?beg@?$_Iosb@H@std@@2W4_Seekdir@12@B DD 00H		; std::_Iosb<int>::beg
;	COMDAT ?binary@?$_Iosb@H@std@@2W4_Openmode@12@B
.rdata	SEGMENT
?binary@?$_Iosb@H@std@@2W4_Openmode@12@B DD 020H	; std::_Iosb<int>::binary
;	COMDAT ?_Noreplace@?$_Iosb@H@std@@2W4_Openmode@12@B
.rdata	SEGMENT
?_Noreplace@?$_Iosb@H@std@@2W4_Openmode@12@B DD 080H	; std::_Iosb<int>::_Noreplace
;	COMDAT ?_Nocreate@?$_Iosb@H@std@@2W4_Openmode@12@B
.rdata	SEGMENT
?_Nocreate@?$_Iosb@H@std@@2W4_Openmode@12@B DD 040H	; std::_Iosb<int>::_Nocreate
;	COMDAT ?trunc@?$_Iosb@H@std@@2W4_Openmode@12@B
.rdata	SEGMENT
?trunc@?$_Iosb@H@std@@2W4_Openmode@12@B DD 010H		; std::_Iosb<int>::trunc
;	COMDAT ?app@?$_Iosb@H@std@@2W4_Openmode@12@B
.rdata	SEGMENT
?app@?$_Iosb@H@std@@2W4_Openmode@12@B DD 08H		; std::_Iosb<int>::app
;	COMDAT ?ate@?$_Iosb@H@std@@2W4_Openmode@12@B
.rdata	SEGMENT
?ate@?$_Iosb@H@std@@2W4_Openmode@12@B DD 04H		; std::_Iosb<int>::ate
;	COMDAT ?out@?$_Iosb@H@std@@2W4_Openmode@12@B
.rdata	SEGMENT
?out@?$_Iosb@H@std@@2W4_Openmode@12@B DD 02H		; std::_Iosb<int>::out
;	COMDAT ?in@?$_Iosb@H@std@@2W4_Openmode@12@B
.rdata	SEGMENT
?in@?$_Iosb@H@std@@2W4_Openmode@12@B DD 01H		; std::_Iosb<int>::in
;	COMDAT ?_Hardfail@?$_Iosb@H@std@@2W4_Iostate@12@B
.rdata	SEGMENT
?_Hardfail@?$_Iosb@H@std@@2W4_Iostate@12@B DD 010H	; std::_Iosb<int>::_Hardfail
;	COMDAT ?badbit@?$_Iosb@H@std@@2W4_Iostate@12@B
.rdata	SEGMENT
?badbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 04H		; std::_Iosb<int>::badbit
;	COMDAT ?failbit@?$_Iosb@H@std@@2W4_Iostate@12@B
.rdata	SEGMENT
?failbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 02H		; std::_Iosb<int>::failbit
;	COMDAT ?eofbit@?$_Iosb@H@std@@2W4_Iostate@12@B
.rdata	SEGMENT
?eofbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 01H		; std::_Iosb<int>::eofbit
;	COMDAT ?goodbit@?$_Iosb@H@std@@2W4_Iostate@12@B
.rdata	SEGMENT
?goodbit@?$_Iosb@H@std@@2W4_Iostate@12@B DD 00H		; std::_Iosb<int>::goodbit
;	COMDAT ?floatfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?floatfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 03000H	; std::_Iosb<int>::floatfield
;	COMDAT ?basefield@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?basefield@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0e00H	; std::_Iosb<int>::basefield
;	COMDAT ?adjustfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?adjustfield@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 01c0H	; std::_Iosb<int>::adjustfield
;	COMDAT ?_Stdio@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?_Stdio@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 08000H	; std::_Iosb<int>::_Stdio
;	COMDAT ?boolalpha@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?boolalpha@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 04000H	; std::_Iosb<int>::boolalpha
;	COMDAT ?hexfloat@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?hexfloat@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 03000H	; std::_Iosb<int>::hexfloat
;	COMDAT ?fixed@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?fixed@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 02000H	; std::_Iosb<int>::fixed
;	COMDAT ?scientific@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?scientific@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 01000H	; std::_Iosb<int>::scientific
;	COMDAT ?hex@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?hex@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0800H		; std::_Iosb<int>::hex
;	COMDAT ?oct@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?oct@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0400H		; std::_Iosb<int>::oct
;	COMDAT ?dec@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?dec@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0200H		; std::_Iosb<int>::dec
;	COMDAT ?internal@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?internal@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 0100H	; std::_Iosb<int>::internal
;	COMDAT ?right@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?right@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 080H		; std::_Iosb<int>::right
;	COMDAT ?left@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?left@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 040H		; std::_Iosb<int>::left
;	COMDAT ?showpos@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?showpos@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 020H	; std::_Iosb<int>::showpos
;	COMDAT ?showpoint@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?showpoint@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 010H	; std::_Iosb<int>::showpoint
;	COMDAT ?showbase@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?showbase@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 08H	; std::_Iosb<int>::showbase
;	COMDAT ?uppercase@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?uppercase@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 04H	; std::_Iosb<int>::uppercase
;	COMDAT ?unitbuf@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?unitbuf@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 02H	; std::_Iosb<int>::unitbuf
;	COMDAT ?skipws@?$_Iosb@H@std@@2W4_Fmtflags@12@B
.rdata	SEGMENT
?skipws@?$_Iosb@H@std@@2W4_Fmtflags@12@B DD 01H		; std::_Iosb<int>::skipws
;	COMDAT ?table_size@?$ctype@D@std@@2IB
.rdata	SEGMENT
?table_size@?$ctype@D@std@@2IB DD 0100H			; std::ctype<char>::table_size
;	COMDAT ?none@?$_Locbase@H@std@@2HB
.rdata	SEGMENT
?none@?$_Locbase@H@std@@2HB DD 00H			; std::_Locbase<int>::none
;	COMDAT ?all@?$_Locbase@H@std@@2HB
.rdata	SEGMENT
?all@?$_Locbase@H@std@@2HB DD 03fH			; std::_Locbase<int>::all
;	COMDAT ?messages@?$_Locbase@H@std@@2HB
.rdata	SEGMENT
?messages@?$_Locbase@H@std@@2HB DD 020H			; std::_Locbase<int>::messages
;	COMDAT ?time@?$_Locbase@H@std@@2HB
.rdata	SEGMENT
?time@?$_Locbase@H@std@@2HB DD 010H			; std::_Locbase<int>::time
;	COMDAT ?numeric@?$_Locbase@H@std@@2HB
.rdata	SEGMENT
?numeric@?$_Locbase@H@std@@2HB DD 08H			; std::_Locbase<int>::numeric
;	COMDAT ?monetary@?$_Locbase@H@std@@2HB
.rdata	SEGMENT
?monetary@?$_Locbase@H@std@@2HB DD 04H			; std::_Locbase<int>::monetary
;	COMDAT ?ctype@?$_Locbase@H@std@@2HB
.rdata	SEGMENT
?ctype@?$_Locbase@H@std@@2HB DD 02H			; std::_Locbase<int>::ctype
;	COMDAT ?collate@?$_Locbase@H@std@@2HB
.rdata	SEGMENT
?collate@?$_Locbase@H@std@@2HB DD 01H			; std::_Locbase<int>::collate
;	COMDAT ?_Rank@?$_Arithmetic_traits@O@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@O@std@@2HB DD 09H		; std::_Arithmetic_traits<long double>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@N@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@N@std@@2HB DD 08H		; std::_Arithmetic_traits<double>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@M@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@M@std@@2HB DD 07H		; std::_Arithmetic_traits<float>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@_K@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@_K@std@@2HB DD 06H		; std::_Arithmetic_traits<unsigned __int64>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@_J@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@_J@std@@2HB DD 06H		; std::_Arithmetic_traits<__int64>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@K@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@K@std@@2HB DD 05H		; std::_Arithmetic_traits<unsigned long>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@J@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@J@std@@2HB DD 05H		; std::_Arithmetic_traits<long>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@I@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@I@std@@2HB DD 04H		; std::_Arithmetic_traits<unsigned int>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@H@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@H@std@@2HB DD 04H		; std::_Arithmetic_traits<int>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@G@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@G@std@@2HB DD 03H		; std::_Arithmetic_traits<unsigned short>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@F@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@F@std@@2HB DD 03H		; std::_Arithmetic_traits<short>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@E@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@E@std@@2HB DD 02H		; std::_Arithmetic_traits<unsigned char>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@C@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@C@std@@2HB DD 02H		; std::_Arithmetic_traits<signed char>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@D@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@D@std@@2HB DD 02H		; std::_Arithmetic_traits<char>::_Rank
;	COMDAT ?_Rank@?$_Arithmetic_traits@_N@std@@2HB
.rdata	SEGMENT
?_Rank@?$_Arithmetic_traits@_N@std@@2HB DD 01H		; std::_Arithmetic_traits<bool>::_Rank
;	COMDAT ?value@?$integral_constant@I$0A@@tr1@std@@2IB
.rdata	SEGMENT
?value@?$integral_constant@I$0A@@tr1@std@@2IB DD 00H	; std::tr1::integral_constant<unsigned int,0>::value
;	COMDAT ?value@?$integral_constant@_N$00@tr1@std@@2_NB
.rdata	SEGMENT
?value@?$integral_constant@_N$00@tr1@std@@2_NB DB 01H	; std::tr1::integral_constant<bool,1>::value
;	COMDAT ?value@?$integral_constant@_N$0A@@tr1@std@@2_NB
.rdata	SEGMENT
?value@?$integral_constant@_N$0A@@tr1@std@@2_NB DB 00H	; std::tr1::integral_constant<bool,0>::value
;	COMDAT ?min_exponent10@?$numeric_limits@O@std@@2HB
.rdata	SEGMENT
?min_exponent10@?$numeric_limits@O@std@@2HB DD 0fffffecdH ; std::numeric_limits<long double>::min_exponent10
;	COMDAT ?min_exponent@?$numeric_limits@O@std@@2HB
.rdata	SEGMENT
?min_exponent@?$numeric_limits@O@std@@2HB DD 0fffffc03H	; std::numeric_limits<long double>::min_exponent
;	COMDAT ?max_exponent10@?$numeric_limits@O@std@@2HB
.rdata	SEGMENT
?max_exponent10@?$numeric_limits@O@std@@2HB DD 0134H	; std::numeric_limits<long double>::max_exponent10
;	COMDAT ?max_exponent@?$numeric_limits@O@std@@2HB
.rdata	SEGMENT
?max_exponent@?$numeric_limits@O@std@@2HB DD 0400H	; std::numeric_limits<long double>::max_exponent
;	COMDAT ?max_digits10@?$numeric_limits@O@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@O@std@@2HB DD 011H	; std::numeric_limits<long double>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@O@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@O@std@@2HB DD 0fH		; std::numeric_limits<long double>::digits10
;	COMDAT ?digits@?$numeric_limits@O@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@O@std@@2HB DD 035H		; std::numeric_limits<long double>::digits
;	COMDAT ?min_exponent10@?$numeric_limits@N@std@@2HB
.rdata	SEGMENT
?min_exponent10@?$numeric_limits@N@std@@2HB DD 0fffffecdH ; std::numeric_limits<double>::min_exponent10
;	COMDAT ?min_exponent@?$numeric_limits@N@std@@2HB
.rdata	SEGMENT
?min_exponent@?$numeric_limits@N@std@@2HB DD 0fffffc03H	; std::numeric_limits<double>::min_exponent
;	COMDAT ?max_exponent10@?$numeric_limits@N@std@@2HB
.rdata	SEGMENT
?max_exponent10@?$numeric_limits@N@std@@2HB DD 0134H	; std::numeric_limits<double>::max_exponent10
;	COMDAT ?max_exponent@?$numeric_limits@N@std@@2HB
.rdata	SEGMENT
?max_exponent@?$numeric_limits@N@std@@2HB DD 0400H	; std::numeric_limits<double>::max_exponent
;	COMDAT ?max_digits10@?$numeric_limits@N@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@N@std@@2HB DD 011H	; std::numeric_limits<double>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@N@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@N@std@@2HB DD 0fH		; std::numeric_limits<double>::digits10
;	COMDAT ?digits@?$numeric_limits@N@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@N@std@@2HB DD 035H		; std::numeric_limits<double>::digits
;	COMDAT ?min_exponent10@?$numeric_limits@M@std@@2HB
.rdata	SEGMENT
?min_exponent10@?$numeric_limits@M@std@@2HB DD 0ffffffdbH ; std::numeric_limits<float>::min_exponent10
;	COMDAT ?min_exponent@?$numeric_limits@M@std@@2HB
.rdata	SEGMENT
?min_exponent@?$numeric_limits@M@std@@2HB DD 0ffffff83H	; std::numeric_limits<float>::min_exponent
;	COMDAT ?max_exponent10@?$numeric_limits@M@std@@2HB
.rdata	SEGMENT
?max_exponent10@?$numeric_limits@M@std@@2HB DD 026H	; std::numeric_limits<float>::max_exponent10
;	COMDAT ?max_exponent@?$numeric_limits@M@std@@2HB
.rdata	SEGMENT
?max_exponent@?$numeric_limits@M@std@@2HB DD 080H	; std::numeric_limits<float>::max_exponent
;	COMDAT ?max_digits10@?$numeric_limits@M@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@M@std@@2HB DD 08H	; std::numeric_limits<float>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@M@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@M@std@@2HB DD 06H		; std::numeric_limits<float>::digits10
;	COMDAT ?digits@?$numeric_limits@M@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@M@std@@2HB DD 018H		; std::numeric_limits<float>::digits
;	COMDAT ?max_digits10@?$numeric_limits@_K@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@_K@std@@2HB DD 015H	; std::numeric_limits<unsigned __int64>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@_K@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@_K@std@@2HB DD 013H		; std::numeric_limits<unsigned __int64>::digits10
;	COMDAT ?digits@?$numeric_limits@_K@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@_K@std@@2HB DD 040H		; std::numeric_limits<unsigned __int64>::digits
;	COMDAT ?is_signed@?$numeric_limits@_K@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@_K@std@@2_NB DB 00H		; std::numeric_limits<unsigned __int64>::is_signed
;	COMDAT ?max_digits10@?$numeric_limits@_J@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@_J@std@@2HB DD 014H	; std::numeric_limits<__int64>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@_J@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@_J@std@@2HB DD 012H		; std::numeric_limits<__int64>::digits10
;	COMDAT ?digits@?$numeric_limits@_J@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@_J@std@@2HB DD 03fH		; std::numeric_limits<__int64>::digits
;	COMDAT ?is_signed@?$numeric_limits@_J@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@_J@std@@2_NB DB 01H		; std::numeric_limits<__int64>::is_signed
;	COMDAT ?max_digits10@?$numeric_limits@K@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@K@std@@2HB DD 0bH	; std::numeric_limits<unsigned long>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@K@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@K@std@@2HB DD 09H		; std::numeric_limits<unsigned long>::digits10
;	COMDAT ?digits@?$numeric_limits@K@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@K@std@@2HB DD 020H		; std::numeric_limits<unsigned long>::digits
;	COMDAT ?is_signed@?$numeric_limits@K@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@K@std@@2_NB DB 00H		; std::numeric_limits<unsigned long>::is_signed
;	COMDAT ?max_digits10@?$numeric_limits@J@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@J@std@@2HB DD 0bH	; std::numeric_limits<long>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@J@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@J@std@@2HB DD 09H		; std::numeric_limits<long>::digits10
;	COMDAT ?digits@?$numeric_limits@J@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@J@std@@2HB DD 01fH		; std::numeric_limits<long>::digits
;	COMDAT ?is_signed@?$numeric_limits@J@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@J@std@@2_NB DB 01H		; std::numeric_limits<long>::is_signed
;	COMDAT ?max_digits10@?$numeric_limits@I@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@I@std@@2HB DD 0bH	; std::numeric_limits<unsigned int>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@I@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@I@std@@2HB DD 09H		; std::numeric_limits<unsigned int>::digits10
;	COMDAT ?digits@?$numeric_limits@I@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@I@std@@2HB DD 020H		; std::numeric_limits<unsigned int>::digits
;	COMDAT ?is_signed@?$numeric_limits@I@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@I@std@@2_NB DB 00H		; std::numeric_limits<unsigned int>::is_signed
;	COMDAT ?max_digits10@?$numeric_limits@H@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@H@std@@2HB DD 0bH	; std::numeric_limits<int>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@H@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@H@std@@2HB DD 09H		; std::numeric_limits<int>::digits10
;	COMDAT ?digits@?$numeric_limits@H@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@H@std@@2HB DD 01fH		; std::numeric_limits<int>::digits
;	COMDAT ?is_signed@?$numeric_limits@H@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@H@std@@2_NB DB 01H		; std::numeric_limits<int>::is_signed
;	COMDAT ?max_digits10@?$numeric_limits@G@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@G@std@@2HB DD 06H	; std::numeric_limits<unsigned short>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@G@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@G@std@@2HB DD 04H		; std::numeric_limits<unsigned short>::digits10
;	COMDAT ?digits@?$numeric_limits@G@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@G@std@@2HB DD 010H		; std::numeric_limits<unsigned short>::digits
;	COMDAT ?is_signed@?$numeric_limits@G@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@G@std@@2_NB DB 00H		; std::numeric_limits<unsigned short>::is_signed
;	COMDAT ?max_digits10@?$numeric_limits@F@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@F@std@@2HB DD 06H	; std::numeric_limits<short>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@F@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@F@std@@2HB DD 04H		; std::numeric_limits<short>::digits10
;	COMDAT ?digits@?$numeric_limits@F@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@F@std@@2HB DD 0fH		; std::numeric_limits<short>::digits
;	COMDAT ?is_signed@?$numeric_limits@F@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@F@std@@2_NB DB 01H		; std::numeric_limits<short>::is_signed
;	COMDAT ?max_digits10@?$numeric_limits@E@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@E@std@@2HB DD 04H	; std::numeric_limits<unsigned char>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@E@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@E@std@@2HB DD 02H		; std::numeric_limits<unsigned char>::digits10
;	COMDAT ?digits@?$numeric_limits@E@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@E@std@@2HB DD 08H		; std::numeric_limits<unsigned char>::digits
;	COMDAT ?is_signed@?$numeric_limits@E@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@E@std@@2_NB DB 00H		; std::numeric_limits<unsigned char>::is_signed
;	COMDAT ?max_digits10@?$numeric_limits@C@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@C@std@@2HB DD 04H	; std::numeric_limits<signed char>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@C@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@C@std@@2HB DD 02H		; std::numeric_limits<signed char>::digits10
;	COMDAT ?digits@?$numeric_limits@C@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@C@std@@2HB DD 07H		; std::numeric_limits<signed char>::digits
;	COMDAT ?is_signed@?$numeric_limits@C@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@C@std@@2_NB DB 01H		; std::numeric_limits<signed char>::is_signed
;	COMDAT ?max_digits10@?$numeric_limits@_N@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@_N@std@@2HB DD 00H	; std::numeric_limits<bool>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@_N@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@_N@std@@2HB DD 00H		; std::numeric_limits<bool>::digits10
;	COMDAT ?digits@?$numeric_limits@_N@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@_N@std@@2HB DD 01H		; std::numeric_limits<bool>::digits
;	COMDAT ?is_signed@?$numeric_limits@_N@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@_N@std@@2_NB DB 00H		; std::numeric_limits<bool>::is_signed
;	COMDAT ?is_modulo@?$numeric_limits@_N@std@@2_NB
.rdata	SEGMENT
?is_modulo@?$numeric_limits@_N@std@@2_NB DB 00H		; std::numeric_limits<bool>::is_modulo
;	COMDAT ?max_digits10@?$numeric_limits@_W@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@_W@std@@2HB DD 06H	; std::numeric_limits<wchar_t>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@_W@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@_W@std@@2HB DD 04H		; std::numeric_limits<wchar_t>::digits10
;	COMDAT ?digits@?$numeric_limits@_W@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@_W@std@@2HB DD 010H		; std::numeric_limits<wchar_t>::digits
;	COMDAT ?is_signed@?$numeric_limits@_W@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@_W@std@@2_NB DB 00H		; std::numeric_limits<wchar_t>::is_signed
;	COMDAT ?max_digits10@?$numeric_limits@D@std@@2HB
.rdata	SEGMENT
?max_digits10@?$numeric_limits@D@std@@2HB DD 04H	; std::numeric_limits<char>::max_digits10
;	COMDAT ?digits10@?$numeric_limits@D@std@@2HB
.rdata	SEGMENT
?digits10@?$numeric_limits@D@std@@2HB DD 02H		; std::numeric_limits<char>::digits10
;	COMDAT ?digits@?$numeric_limits@D@std@@2HB
.rdata	SEGMENT
?digits@?$numeric_limits@D@std@@2HB DD 07H		; std::numeric_limits<char>::digits
;	COMDAT ?is_signed@?$numeric_limits@D@std@@2_NB
.rdata	SEGMENT
?is_signed@?$numeric_limits@D@std@@2_NB DB 01H		; std::numeric_limits<char>::is_signed
;	COMDAT ?radix@_Num_float_base@std@@2HB
.rdata	SEGMENT
?radix@_Num_float_base@std@@2HB DD 02H			; std::_Num_float_base::radix
;	COMDAT ?round_style@_Num_float_base@std@@2W4float_round_style@2@B
.rdata	SEGMENT
?round_style@_Num_float_base@std@@2W4float_round_style@2@B DD 01H ; std::_Num_float_base::round_style
;	COMDAT ?traps@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?traps@_Num_float_base@std@@2_NB DB 01H			; std::_Num_float_base::traps
;	COMDAT ?tinyness_before@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?tinyness_before@_Num_float_base@std@@2_NB DB 01H	; std::_Num_float_base::tinyness_before
;	COMDAT ?is_specialized@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?is_specialized@_Num_float_base@std@@2_NB DB 01H	; std::_Num_float_base::is_specialized
;	COMDAT ?is_signed@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?is_signed@_Num_float_base@std@@2_NB DB 01H		; std::_Num_float_base::is_signed
;	COMDAT ?is_modulo@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?is_modulo@_Num_float_base@std@@2_NB DB 00H		; std::_Num_float_base::is_modulo
;	COMDAT ?is_integer@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?is_integer@_Num_float_base@std@@2_NB DB 00H		; std::_Num_float_base::is_integer
;	COMDAT ?is_iec559@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?is_iec559@_Num_float_base@std@@2_NB DB 01H		; std::_Num_float_base::is_iec559
;	COMDAT ?is_exact@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?is_exact@_Num_float_base@std@@2_NB DB 00H		; std::_Num_float_base::is_exact
;	COMDAT ?is_bounded@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?is_bounded@_Num_float_base@std@@2_NB DB 01H		; std::_Num_float_base::is_bounded
;	COMDAT ?has_signaling_NaN@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?has_signaling_NaN@_Num_float_base@std@@2_NB DB 01H	; std::_Num_float_base::has_signaling_NaN
;	COMDAT ?has_quiet_NaN@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?has_quiet_NaN@_Num_float_base@std@@2_NB DB 01H		; std::_Num_float_base::has_quiet_NaN
;	COMDAT ?has_infinity@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?has_infinity@_Num_float_base@std@@2_NB DB 01H		; std::_Num_float_base::has_infinity
;	COMDAT ?has_denorm_loss@_Num_float_base@std@@2_NB
.rdata	SEGMENT
?has_denorm_loss@_Num_float_base@std@@2_NB DB 01H	; std::_Num_float_base::has_denorm_loss
;	COMDAT ?has_denorm@_Num_float_base@std@@2W4float_denorm_style@2@B
.rdata	SEGMENT
?has_denorm@_Num_float_base@std@@2W4float_denorm_style@2@B DD 01H ; std::_Num_float_base::has_denorm
;	COMDAT ?radix@_Num_int_base@std@@2HB
.rdata	SEGMENT
?radix@_Num_int_base@std@@2HB DD 02H			; std::_Num_int_base::radix
;	COMDAT ?is_specialized@_Num_int_base@std@@2_NB
.rdata	SEGMENT
?is_specialized@_Num_int_base@std@@2_NB DB 01H		; std::_Num_int_base::is_specialized
;	COMDAT ?is_modulo@_Num_int_base@std@@2_NB
.rdata	SEGMENT
?is_modulo@_Num_int_base@std@@2_NB DB 01H		; std::_Num_int_base::is_modulo
;	COMDAT ?is_integer@_Num_int_base@std@@2_NB
.rdata	SEGMENT
?is_integer@_Num_int_base@std@@2_NB DB 01H		; std::_Num_int_base::is_integer
;	COMDAT ?is_exact@_Num_int_base@std@@2_NB
.rdata	SEGMENT
?is_exact@_Num_int_base@std@@2_NB DB 01H		; std::_Num_int_base::is_exact
;	COMDAT ?is_bounded@_Num_int_base@std@@2_NB
.rdata	SEGMENT
?is_bounded@_Num_int_base@std@@2_NB DB 01H		; std::_Num_int_base::is_bounded
;	COMDAT ?radix@_Num_base@std@@2HB
.rdata	SEGMENT
?radix@_Num_base@std@@2HB DD 00H			; std::_Num_base::radix
;	COMDAT ?min_exponent10@_Num_base@std@@2HB
.rdata	SEGMENT
?min_exponent10@_Num_base@std@@2HB DD 00H		; std::_Num_base::min_exponent10
;	COMDAT ?min_exponent@_Num_base@std@@2HB
.rdata	SEGMENT
?min_exponent@_Num_base@std@@2HB DD 00H			; std::_Num_base::min_exponent
;	COMDAT ?max_exponent10@_Num_base@std@@2HB
.rdata	SEGMENT
?max_exponent10@_Num_base@std@@2HB DD 00H		; std::_Num_base::max_exponent10
;	COMDAT ?max_exponent@_Num_base@std@@2HB
.rdata	SEGMENT
?max_exponent@_Num_base@std@@2HB DD 00H			; std::_Num_base::max_exponent
;	COMDAT ?max_digits10@_Num_base@std@@2HB
.rdata	SEGMENT
?max_digits10@_Num_base@std@@2HB DD 00H			; std::_Num_base::max_digits10
;	COMDAT ?digits10@_Num_base@std@@2HB
.rdata	SEGMENT
?digits10@_Num_base@std@@2HB DD 00H			; std::_Num_base::digits10
;	COMDAT ?digits@_Num_base@std@@2HB
.rdata	SEGMENT
?digits@_Num_base@std@@2HB DD 00H			; std::_Num_base::digits
;	COMDAT ?round_style@_Num_base@std@@2W4float_round_style@2@B
.rdata	SEGMENT
?round_style@_Num_base@std@@2W4float_round_style@2@B DD 00H ; std::_Num_base::round_style
;	COMDAT ?traps@_Num_base@std@@2_NB
.rdata	SEGMENT
?traps@_Num_base@std@@2_NB DB 00H			; std::_Num_base::traps
;	COMDAT ?tinyness_before@_Num_base@std@@2_NB
.rdata	SEGMENT
?tinyness_before@_Num_base@std@@2_NB DB 00H		; std::_Num_base::tinyness_before
;	COMDAT ?is_specialized@_Num_base@std@@2_NB
.rdata	SEGMENT
?is_specialized@_Num_base@std@@2_NB DB 00H		; std::_Num_base::is_specialized
;	COMDAT ?is_signed@_Num_base@std@@2_NB
.rdata	SEGMENT
?is_signed@_Num_base@std@@2_NB DB 00H			; std::_Num_base::is_signed
;	COMDAT ?is_modulo@_Num_base@std@@2_NB
.rdata	SEGMENT
?is_modulo@_Num_base@std@@2_NB DB 00H			; std::_Num_base::is_modulo
;	COMDAT ?is_integer@_Num_base@std@@2_NB
.rdata	SEGMENT
?is_integer@_Num_base@std@@2_NB DB 00H			; std::_Num_base::is_integer
;	COMDAT ?is_iec559@_Num_base@std@@2_NB
.rdata	SEGMENT
?is_iec559@_Num_base@std@@2_NB DB 00H			; std::_Num_base::is_iec559
;	COMDAT ?is_exact@_Num_base@std@@2_NB
.rdata	SEGMENT
?is_exact@_Num_base@std@@2_NB DB 00H			; std::_Num_base::is_exact
;	COMDAT ?is_bounded@_Num_base@std@@2_NB
.rdata	SEGMENT
?is_bounded@_Num_base@std@@2_NB DB 00H			; std::_Num_base::is_bounded
;	COMDAT ?has_signaling_NaN@_Num_base@std@@2_NB
.rdata	SEGMENT
?has_signaling_NaN@_Num_base@std@@2_NB DB 00H		; std::_Num_base::has_signaling_NaN
;	COMDAT ?has_quiet_NaN@_Num_base@std@@2_NB
.rdata	SEGMENT
?has_quiet_NaN@_Num_base@std@@2_NB DB 00H		; std::_Num_base::has_quiet_NaN
;	COMDAT ?has_infinity@_Num_base@std@@2_NB
.rdata	SEGMENT
?has_infinity@_Num_base@std@@2_NB DB 00H		; std::_Num_base::has_infinity
;	COMDAT ?has_denorm_loss@_Num_base@std@@2_NB
.rdata	SEGMENT
?has_denorm_loss@_Num_base@std@@2_NB DB 00H		; std::_Num_base::has_denorm_loss
;	COMDAT ?has_denorm@_Num_base@std@@2W4float_denorm_style@2@B
.rdata	SEGMENT
?has_denorm@_Num_base@std@@2W4float_denorm_style@2@B DD 00H ; std::_Num_base::has_denorm
;	COMDAT ?g_XMUnsignedFix@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMUnsignedFix@@3UXMVECTORF32@@B DD 04f000000r ; 2.14748e+009 ; g_XMUnsignedFix
	DD	04f000000r			; 2.14748e+009
	DD	04f000000r			; 2.14748e+009
	DD	04f000000r			; 2.14748e+009
;	COMDAT ?g_XMMaxUInt@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMMaxUInt@@3UXMVECTORF32@@B DD 04f7fffffr	; 4.29497e+009 ; g_XMMaxUInt
	DD	04f7fffffr			; 4.29497e+009
	DD	04f7fffffr			; 4.29497e+009
	DD	04f7fffffr			; 4.29497e+009
;	COMDAT ?g_XMMaxInt@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMMaxInt@@3UXMVECTORF32@@B DD 04effffffr	; 2.14748e+009 ; g_XMMaxInt
	DD	04effffffr			; 2.14748e+009
	DD	04effffffr			; 2.14748e+009
	DD	04effffffr			; 2.14748e+009
;	COMDAT ?g_XMFixUnsigned@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMFixUnsigned@@3UXMVECTORF32@@B DD 04f000000r ; 2.14748e+009 ; g_XMFixUnsigned
	DD	04f000000r			; 2.14748e+009
	DD	04f000000r			; 2.14748e+009
	DD	04f000000r			; 2.14748e+009
;	COMDAT ?g_XMAddByte4@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMAddByte4@@3UXMVECTORF32@@B DD 0c3000000r	; -128	; g_XMAddByte4
	DD	0c7000000r			; -32768
	DD	0cb000000r			; -8.38861e+006
	DD	000000000r			; 0
;	COMDAT ?g_XMXorByte4@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMXorByte4@@3UXMVECTORI32@@B DD 080H			; g_XMXorByte4
	DD	08000H
	DD	0800000H
	DD	00H
;	COMDAT ?g_XMMaskByte4@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskByte4@@3UXMVECTORI32@@B DD 0ffH		; g_XMMaskByte4
	DD	0ff00H
	DD	0ff0000H
	DD	0ff000000H
;	COMDAT ?g_XMMulDec4@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMMulDec4@@3UXMVECTORF32@@B DD 03f800000r	; 1	; g_XMMulDec4
	DD	03a800000r			; 0.000976563
	DD	035800000r			; 9.53674e-007
	DD	030800000r			; 9.31323e-010
;	COMDAT ?g_XMAddDec4@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMAddDec4@@3UXMVECTORF32@@B DD 0c4000000r	; -512	; g_XMAddDec4
	DD	0c9000000r			; -524288
	DD	0ce000000r			; -5.36871e+008
	DD	000000000r			; 0
;	COMDAT ?g_XMAddUDec4@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMAddUDec4@@3UXMVECTORF32@@B DD 000000000r	; 0	; g_XMAddUDec4
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	04f000000r			; 2.14748e+009
;	COMDAT ?g_XMXorDec4@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMXorDec4@@3UXMVECTORI32@@B DD 0200H			; g_XMXorDec4
	DD	080000H
	DD	020000000H
	DD	00H
;	COMDAT ?g_XMMaskDec4@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskDec4@@3UXMVECTORI32@@B DD 03ffH		; g_XMMaskDec4
	DD	0ffc00H
	DD	03ff00000H
	DD	0c0000000H
;	COMDAT ?g_XMMulIco4@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMMulIco4@@3UXMVECTORF32@@B DD 03f800000r	; 1	; g_XMMulIco4
	DD	039800000r			; 0.000244141
	DD	03f800000r			; 1
	DD	031800000r			; 3.72529e-009
;	COMDAT ?g_XMAddIco4@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMAddIco4@@3UXMVECTORF32@@B DD 0c9000000r	; -524288 ; g_XMAddIco4
	DD	000000000r			; 0
	DD	0c9000000r			; -524288
	DD	000000000r			; 0
;	COMDAT ?g_XMAddUIco4@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMAddUIco4@@3UXMVECTORF32@@B DD 000000000r	; 0	; g_XMAddUIco4
	DD	04f000000r			; 2.14748e+009
	DD	000000000r			; 0
	DD	04f000000r			; 2.14748e+009
;	COMDAT ?g_XMAddXIco4@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMAddXIco4@@3UXMVECTORF32@@B DD 0c9000000r	; -524288 ; g_XMAddXIco4
	DD	000000000r			; 0
	DD	0c9000000r			; -524288
	DD	04f000000r			; 2.14748e+009
;	COMDAT ?g_XMXorIco4@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMXorIco4@@3UXMVECTORI32@@B DD 080000H		; g_XMXorIco4
	DD	00H
	DD	080000H
	DD	00H
;	COMDAT ?g_XMXorXIco4@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMXorXIco4@@3UXMVECTORI32@@B DD 080000H		; g_XMXorXIco4
	DD	00H
	DD	080000H
	DD	080000000H
;	COMDAT ?g_XMMaskIco4@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskIco4@@3UXMVECTORI32@@B DD 0fffffH		; g_XMMaskIco4
	DD	0fffff000H
	DD	0fffffH
	DD	0f0000000H
;	COMDAT ?g_XMXorDHen3@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMXorDHen3@@3UXMVECTORI32@@B DD 0200H		; g_XMXorDHen3
	DD	0100000H
	DD	00H
	DD	00H
;	COMDAT ?g_XMXorHenD3@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMXorHenD3@@3UXMVECTORI32@@B DD 0400H		; g_XMXorHenD3
	DD	0200000H
	DD	00H
	DD	00H
;	COMDAT ?g_XMMulDHen3@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMMulDHen3@@3UXMVECTORF32@@B DD 03f800000r	; 1	; g_XMMulDHen3
	DD	03a800000r			; 0.000976563
	DD	035000000r			; 4.76837e-007
	DD	000000000r			; 0
;	COMDAT ?g_XMMulHenD3@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMMulHenD3@@3UXMVECTORF32@@B DD 03f800000r	; 1	; g_XMMulHenD3
	DD	03a000000r			; 0.000488281
	DD	034800000r			; 2.38419e-007
	DD	000000000r			; 0
;	COMDAT ?g_XMAddDHen3@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMAddDHen3@@3UXMVECTORF32@@B DD 0c4000000r	; -512	; g_XMAddDHen3
	DD	0c9800000r			; -1.04858e+006
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMAddHenD3@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMAddHenD3@@3UXMVECTORF32@@B DD 0c4800000r	; -1024	; g_XMAddHenD3
	DD	0ca000000r			; -2.09715e+006
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMAddUHenD3@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMAddUHenD3@@3UXMVECTORF32@@B DD 000000000r	; 0	; g_XMAddUHenD3
	DD	000000000r			; 0
	DD	04f000000r			; 2.14748e+009
	DD	000000000r			; 0
;	COMDAT ?g_XMMaskDHen3@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskDHen3@@3UXMVECTORI32@@B DD 03ffH		; g_XMMaskDHen3
	DD	01ffc00H
	DD	0ffe00000H
	DD	00H
;	COMDAT ?g_XMMaskHenD3@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskHenD3@@3UXMVECTORI32@@B DD 07ffH		; g_XMMaskHenD3
	DD	03ff800H
	DD	0ffc00000H
	DD	00H
;	COMDAT ?g_XMFlipYW@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFlipYW@@3UXMVECTORI32@@B DD 00H			; g_XMFlipYW
	DD	080000000H
	DD	00H
	DD	080000000H
;	COMDAT ?g_XMFlipZW@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFlipZW@@3UXMVECTORI32@@B DD 00H			; g_XMFlipZW
	DD	00H
	DD	080000000H
	DD	080000000H
;	COMDAT ?g_XMFlipYZ@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFlipYZ@@3UXMVECTORI32@@B DD 00H			; g_XMFlipYZ
	DD	080000000H
	DD	080000000H
	DD	00H
;	COMDAT ?g_XMFlipW@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFlipW@@3UXMVECTORI32@@B DD 00H			; g_XMFlipW
	DD	00H
	DD	00H
	DD	080000000H
;	COMDAT ?g_XMFlipZ@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFlipZ@@3UXMVECTORI32@@B DD 00H			; g_XMFlipZ
	DD	00H
	DD	080000000H
	DD	00H
;	COMDAT ?g_XMFlipY@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFlipY@@3UXMVECTORI32@@B DD 00H			; g_XMFlipY
	DD	080000000H
	DD	00H
	DD	00H
;	COMDAT ?g_XMFixupY16W16@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMFixupY16W16@@3UXMVECTORF32@@B DD 03f800000r ; 1	; g_XMFixupY16W16
	DD	03f800000r			; 1
	DD	037800000r			; 1.52588e-005
	DD	037800000r			; 1.52588e-005
;	COMDAT ?g_XMFixupY16@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMFixupY16@@3UXMVECTORF32@@B DD 03f800000r	; 1	; g_XMFixupY16
	DD	037800000r			; 1.52588e-005
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMPermute0Z0W1Z1W@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMPermute0Z0W1Z1W@@3UXMVECTORI32@@B DD 08090a0bH	; g_XMPermute0Z0W1Z1W
	DD	0c0d0e0fH
	DD	018191a1bH
	DD	01c1d1e1fH
;	COMDAT ?g_XMPermute0X0Y1X1Y@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMPermute0X0Y1X1Y@@3UXMVECTORI32@@B DD 010203H	; g_XMPermute0X0Y1X1Y
	DD	04050607H
	DD	010111213H
	DD	014151617H
;	COMDAT ?g_XMSwizzleZXYW@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMSwizzleZXYW@@3UXMVECTORI32@@B DD 08090a0bH		; g_XMSwizzleZXYW
	DD	010203H
	DD	04050607H
	DD	0c0d0e0fH
;	COMDAT ?g_XMSwizzleYZXW@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMSwizzleYZXW@@3UXMVECTORI32@@B DD 04050607H		; g_XMSwizzleYZXW
	DD	08090a0bH
	DD	010203H
	DD	0c0d0e0fH
;	COMDAT ?g_XMSwizzleYXZW@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMSwizzleYXZW@@3UXMVECTORI32@@B DD 04050607H		; g_XMSwizzleYXZW
	DD	010203H
	DD	08090a0bH
	DD	0c0d0e0fH
;	COMDAT ?g_XMSwizzleXYZX@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMSwizzleXYZX@@3UXMVECTORI32@@B DD 010203H		; g_XMSwizzleXYZX
	DD	04050607H
	DD	08090a0bH
	DD	010203H
;	COMDAT ?g_XMSwizzleXYXY@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMSwizzleXYXY@@3UXMVECTORI32@@B DD 010203H		; g_XMSwizzleXYXY
	DD	04050607H
	DD	010203H
	DD	04050607H
;	COMDAT ?g_XMSelect1110@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMSelect1110@@3UXMVECTORI32@@B DD 0ffffffffH		; g_XMSelect1110
	DD	0ffffffffH
	DD	0ffffffffH
	DD	00H
;	COMDAT ?g_XMSelect1100@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMSelect1100@@3UXMVECTORI32@@B DD 0ffffffffH		; g_XMSelect1100
	DD	0ffffffffH
	DD	00H
	DD	00H
;	COMDAT ?g_XMSelect1000@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMSelect1000@@3UXMVECTORI32@@B DD 0ffffffffH		; g_XMSelect1000
	DD	00H
	DD	00H
	DD	00H
;	COMDAT ?g_XMOneHalfMinusEpsilon@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMOneHalfMinusEpsilon@@3UXMVECTORI32@@B DD 03efffffdH ; g_XMOneHalfMinusEpsilon
	DD	03efffffdH
	DD	03efffffdH
	DD	03efffffdH
;	COMDAT ?g_XMSelect1010@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMSelect1010@@3UXMVECTORI32@@B DD 0ffffffffH		; g_XMSelect1010
	DD	00H
	DD	0ffffffffH
	DD	00H
;	COMDAT ?g_XMSelect0101@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMSelect0101@@3UXMVECTORI32@@B DD 00H		; g_XMSelect0101
	DD	0ffffffffH
	DD	00H
	DD	0ffffffffH
;	COMDAT ?g_XMNegateW@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegateW@@3UXMVECTORF32@@B DD 03f800000r	; 1	; g_XMNegateW
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
;	COMDAT ?g_XMNegateZ@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegateZ@@3UXMVECTORF32@@B DD 03f800000r	; 1	; g_XMNegateZ
	DD	03f800000r			; 1
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
;	COMDAT ?g_XMNegateY@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegateY@@3UXMVECTORF32@@B DD 03f800000r	; 1	; g_XMNegateY
	DD	0bf800000r			; -1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
;	COMDAT ?g_XMNegateX@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegateX@@3UXMVECTORF32@@B DD 0bf800000r	; -1	; g_XMNegateX
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
;	COMDAT ?g_XMMaskByte@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskByte@@3UXMVECTORI32@@B DD 0ffH			; g_XMMaskByte
	DD	0ffH
	DD	0ffH
	DD	0ffH
;	COMDAT ?g_XMNoFraction@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNoFraction@@3UXMVECTORF32@@B DD 04b000000r	; 8.38861e+006 ; g_XMNoFraction
	DD	04b000000r			; 8.38861e+006
	DD	04b000000r			; 8.38861e+006
	DD	04b000000r			; 8.38861e+006
;	COMDAT ?g_XMNormalizeX16Y16Z16W16@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNormalizeX16Y16Z16W16@@3UXMVECTORF32@@B DD 038000100r ; 3.05185e-005 ; g_XMNormalizeX16Y16Z16W16
	DD	038000100r			; 3.05185e-005
	DD	030000100r			; 4.65675e-010
	DD	030000100r			; 4.65675e-010
;	COMDAT ?g_XMFixX16Y16Z16W16@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMFixX16Y16Z16W16@@3UXMVECTORF32@@B DD 0c7000000r ; -32768 ; g_XMFixX16Y16Z16W16
	DD	0c7000000r			; -32768
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMFlipX16Y16Z16W16@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFlipX16Y16Z16W16@@3UXMVECTORI32@@B DD 08000H	; g_XMFlipX16Y16Z16W16
	DD	08000H
	DD	00H
	DD	00H
;	COMDAT ?g_XMMaskX16Y16Z16W16@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskX16Y16Z16W16@@3UXMVECTORI32@@B DD 0ffffH	; g_XMMaskX16Y16Z16W16
	DD	0ffffH
	DD	0ffff0000H
	DD	0ffff0000H
;	COMDAT ?g_XMNormalizeX16Y16@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNormalizeX16Y16@@3UXMVECTORF32@@B DD 038000100r ; 3.05185e-005 ; g_XMNormalizeX16Y16
	DD	030000100r			; 4.65675e-010
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMFixX16Y16@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMFixX16Y16@@3UXMVECTORF32@@B DD 0c7000000r	; -32768 ; g_XMFixX16Y16
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMFlipX16Y16@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFlipX16Y16@@3UXMVECTORI32@@B DD 08000H		; g_XMFlipX16Y16
	DD	00H
	DD	00H
	DD	00H
;	COMDAT ?g_XMMaskX16Y16@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskX16Y16@@3UXMVECTORI32@@B DD 0ffffH		; g_XMMaskX16Y16
	DD	0ffff0000H
	DD	00H
	DD	00H
;	COMDAT ?g_XMNormalizeA2B10G10R10@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNormalizeA2B10G10R10@@3UXMVECTORF32@@B DD 03b004020r ; 0.00195695 ; g_XMNormalizeA2B10G10R10
	DD	036004020r			; 1.91108e-006
	DD	031004020r			; 1.86629e-009
	DD	02faaaaabr			; 3.10441e-010
;	COMDAT ?g_XMFixAA2B10G10R10@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMFixAA2B10G10R10@@3UXMVECTORF32@@B DD 0c4000000r ; -512 ; g_XMFixAA2B10G10R10
	DD	0c9000000r			; -524288
	DD	0ce000000r			; -5.36871e+008
	DD	04f000000r			; 2.14748e+009
;	COMDAT ?g_XMFlipA2B10G10R10@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFlipA2B10G10R10@@3UXMVECTORI32@@B DD 0200H		; g_XMFlipA2B10G10R10
	DD	080000H
	DD	020000000H
	DD	080000000H
;	COMDAT ?g_XMMaskA2B10G10R10@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskA2B10G10R10@@3UXMVECTORI32@@B DD 03ffH		; g_XMMaskA2B10G10R10
	DD	0ffc00H
	DD	03ff00000H
	DD	0c0000000H
;	COMDAT ?g_XMNormalizeA8R8G8B8@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNormalizeA8R8G8B8@@3UXMVECTORF32@@B DD 033808081r ; 5.98384e-008 ; g_XMNormalizeA8R8G8B8
	DD	037808081r			; 1.53186e-005
	DD	03b808081r			; 0.00392157
	DD	02f808081r			; 2.33744e-010
;	COMDAT ?g_XMFixAA8R8G8B8@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMFixAA8R8G8B8@@3UXMVECTORF32@@B DD 000000000r ; 0	; g_XMFixAA8R8G8B8
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	04f000000r			; 2.14748e+009
;	COMDAT ?g_XMFlipA8R8G8B8@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFlipA8R8G8B8@@3UXMVECTORI32@@B DD 00H		; g_XMFlipA8R8G8B8
	DD	00H
	DD	00H
	DD	080000000H
;	COMDAT ?g_XMMaskA8R8G8B8@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskA8R8G8B8@@3UXMVECTORI32@@B DD 0ff0000H		; g_XMMaskA8R8G8B8
	DD	0ff00H
	DD	0ffH
	DD	0ff000000H
;	COMDAT ?g_XMNegOneMask@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMNegOneMask@@3UXMVECTORI32@@B DD 0ffffffffH		; g_XMNegOneMask
	DD	0ffffffffH
	DD	0ffffffffH
	DD	0ffffffffH
;	COMDAT ?g_XMFltMax@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFltMax@@3UXMVECTORI32@@B DD 07f7fffffH		; g_XMFltMax
	DD	07f7fffffH
	DD	07f7fffffH
	DD	07f7fffffH
;	COMDAT ?g_XMFltMin@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMFltMin@@3UXMVECTORI32@@B DD 0800000H		; g_XMFltMin
	DD	0800000H
	DD	0800000H
	DD	0800000H
;	COMDAT ?g_XMAbsMask@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMAbsMask@@3UXMVECTORI32@@B DD 07fffffffH		; g_XMAbsMask
	DD	07fffffffH
	DD	07fffffffH
	DD	07fffffffH
;	COMDAT ?g_XMQNaNTest@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMQNaNTest@@3UXMVECTORI32@@B DD 07fffffH		; g_XMQNaNTest
	DD	07fffffH
	DD	07fffffH
	DD	07fffffH
;	COMDAT ?g_XMQNaN@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMQNaN@@3UXMVECTORI32@@B DD 07fc00000H		; g_XMQNaN
	DD	07fc00000H
	DD	07fc00000H
	DD	07fc00000H
;	COMDAT ?g_XMInfinity@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMInfinity@@3UXMVECTORI32@@B DD 07f800000H		; g_XMInfinity
	DD	07f800000H
	DD	07f800000H
	DD	07f800000H
;	COMDAT ?g_XMEpsilon@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMEpsilon@@3UXMVECTORF32@@B DD 034000000r	; 1.19209e-007 ; g_XMEpsilon
	DD	034000000r			; 1.19209e-007
	DD	034000000r			; 1.19209e-007
	DD	034000000r			; 1.19209e-007
;	COMDAT ?g_XMReciprocalTwoPi@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMReciprocalTwoPi@@3UXMVECTORF32@@B DD 03e22f983r ; 0.159155 ; g_XMReciprocalTwoPi
	DD	03e22f983r			; 0.159155
	DD	03e22f983r			; 0.159155
	DD	03e22f983r			; 0.159155
;	COMDAT ?g_XMTwoPi@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMTwoPi@@3UXMVECTORF32@@B DD 040c90fdbr	; 6.28319 ; g_XMTwoPi
	DD	040c90fdbr			; 6.28319
	DD	040c90fdbr			; 6.28319
	DD	040c90fdbr			; 6.28319
;	COMDAT ?g_XMReciprocalPi@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMReciprocalPi@@3UXMVECTORF32@@B DD 03ea2f983r ; 0.31831 ; g_XMReciprocalPi
	DD	03ea2f983r			; 0.31831
	DD	03ea2f983r			; 0.31831
	DD	03ea2f983r			; 0.31831
;	COMDAT ?g_XMPi@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMPi@@3UXMVECTORF32@@B DD 040490fdbr		; 3.14159 ; g_XMPi
	DD	040490fdbr			; 3.14159
	DD	040490fdbr			; 3.14159
	DD	040490fdbr			; 3.14159
;	COMDAT ?g_XMHalfPi@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMHalfPi@@3UXMVECTORF32@@B DD 03fc90fdbr	; 1.5708 ; g_XMHalfPi
	DD	03fc90fdbr			; 1.5708
	DD	03fc90fdbr			; 1.5708
	DD	03fc90fdbr			; 1.5708
;	COMDAT ?g_XMNegativePi@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegativePi@@3UXMVECTORF32@@B DD 0c0490fdbr	; -3.14159 ; g_XMNegativePi
	DD	0c0490fdbr			; -3.14159
	DD	0c0490fdbr			; -3.14159
	DD	0c0490fdbr			; -3.14159
;	COMDAT ?g_XMNegativeTwoPi@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegativeTwoPi@@3UXMVECTORF32@@B DD 0c0c90fdbr ; -6.28319 ; g_XMNegativeTwoPi
	DD	0c0c90fdbr			; -6.28319
	DD	0c0c90fdbr			; -6.28319
	DD	0c0c90fdbr			; -6.28319
;	COMDAT ?g_XMNegativeOneHalf@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegativeOneHalf@@3UXMVECTORF32@@B DD 0bf000000r ; -0.5 ; g_XMNegativeOneHalf
	DD	0bf000000r			; -0.5
	DD	0bf000000r			; -0.5
	DD	0bf000000r			; -0.5
;	COMDAT ?g_XMOneHalf@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMOneHalf@@3UXMVECTORF32@@B DD 03f000000r	; 0.5	; g_XMOneHalf
	DD	03f000000r			; 0.5
	DD	03f000000r			; 0.5
	DD	03f000000r			; 0.5
;	COMDAT ?g_XMNegativeOne@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegativeOne@@3UXMVECTORF32@@B DD 0bf800000r ; -1	; g_XMNegativeOne
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
	DD	0bf800000r			; -1
;	COMDAT ?g_XMZero@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMZero@@3UXMVECTORF32@@B DD 000000000r	; 0	; g_XMZero
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMOne3@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMOne3@@3UXMVECTORF32@@B DD 03f800000r	; 1	; g_XMOne3
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	000000000r			; 0
;	COMDAT ?g_XMOne@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMOne@@3UXMVECTORF32@@B DD 03f800000r	; 1	; g_XMOne
	DD	03f800000r			; 1
	DD	03f800000r			; 1
	DD	03f800000r			; 1
;	COMDAT ?g_XMMaskW@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskW@@3UXMVECTORI32@@B DD 00H			; g_XMMaskW
	DD	00H
	DD	00H
	DD	0ffffffffH
;	COMDAT ?g_XMMaskZ@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskZ@@3UXMVECTORI32@@B DD 00H			; g_XMMaskZ
	DD	00H
	DD	0ffffffffH
	DD	00H
;	COMDAT ?g_XMMaskY@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskY@@3UXMVECTORI32@@B DD 00H			; g_XMMaskY
	DD	0ffffffffH
	DD	00H
	DD	00H
;	COMDAT ?g_XMMaskX@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMaskX@@3UXMVECTORI32@@B DD 0ffffffffH		; g_XMMaskX
	DD	00H
	DD	00H
	DD	00H
;	COMDAT ?g_XMMask3@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMMask3@@3UXMVECTORI32@@B DD 0ffffffffH		; g_XMMask3
	DD	0ffffffffH
	DD	0ffffffffH
	DD	00H
;	COMDAT ?g_XMNegate3@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMNegate3@@3UXMVECTORI32@@B DD 080000000H		; g_XMNegate3
	DD	080000000H
	DD	080000000H
	DD	00H
;	COMDAT ?g_XMNegativeZero@@3UXMVECTORI32@@B
.rdata	SEGMENT
?g_XMNegativeZero@@3UXMVECTORI32@@B DD 080000000H	; g_XMNegativeZero
	DD	080000000H
	DD	080000000H
	DD	080000000H
;	COMDAT ?g_XMNegIdentityR3@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegIdentityR3@@3UXMVECTORF32@@B DD 000000000r ; 0	; g_XMNegIdentityR3
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	0bf800000r			; -1
;	COMDAT ?g_XMNegIdentityR2@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegIdentityR2@@3UXMVECTORF32@@B DD 000000000r ; 0	; g_XMNegIdentityR2
	DD	000000000r			; 0
	DD	0bf800000r			; -1
	DD	000000000r			; 0
;	COMDAT ?g_XMNegIdentityR1@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegIdentityR1@@3UXMVECTORF32@@B DD 000000000r ; 0	; g_XMNegIdentityR1
	DD	0bf800000r			; -1
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMNegIdentityR0@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMNegIdentityR0@@3UXMVECTORF32@@B DD 0bf800000r ; -1	; g_XMNegIdentityR0
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMIdentityR3@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMIdentityR3@@3UXMVECTORF32@@B DD 000000000r	; 0	; g_XMIdentityR3
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	03f800000r			; 1
;	COMDAT ?g_XMIdentityR2@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMIdentityR2@@3UXMVECTORF32@@B DD 000000000r	; 0	; g_XMIdentityR2
	DD	000000000r			; 0
	DD	03f800000r			; 1
	DD	000000000r			; 0
;	COMDAT ?g_XMIdentityR1@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMIdentityR1@@3UXMVECTORF32@@B DD 000000000r	; 0	; g_XMIdentityR1
	DD	03f800000r			; 1
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMIdentityR0@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMIdentityR0@@3UXMVECTORF32@@B DD 03f800000r	; 1	; g_XMIdentityR0
	DD	000000000r			; 0
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMPiConstants0@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMPiConstants0@@3UXMVECTORF32@@B DD 040490fdbr ; 3.14159 ; g_XMPiConstants0
	DD	040c90fdbr			; 6.28319
	DD	03ea2f983r			; 0.31831
	DD	03e22f983r			; 0.159155
;	COMDAT ?g_XMASinEstConstants@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMASinEstConstants@@3UXMVECTORF32@@B DD 03f800001r ; 1 ; g_XMASinEstConstants
	DD	03fc90fdbr			; 1.5708
	DD	000000000r			; 0
	DD	000000000r			; 0
;	COMDAT ?g_XMASinEstCoefficients@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMASinEstCoefficients@@3UXMVECTORF32@@B DD 0bfae4ee5r ; -1.36178 ; g_XMASinEstCoefficients
	DD	0401849a5r			; 2.37949
	DD	0bf4ee811r			; -0.808229
	DD	03e8e8fb5r			; 0.27844
;	COMDAT ?g_XMATanEstCoefficients@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMATanEstCoefficients@@3UXMVECTORF32@@B DD 03f44dc79r ; 0.768989 ; g_XMATanEstCoefficients
	DD	03f8d6834r			; 1.10474
	DD	03f5dbe43r			; 0.866184
	DD	03fc90fdbr			; 1.5708
;	COMDAT ?g_XMTanEstCoefficients@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMTanEstCoefficients@@3UXMVECTORF32@@B DD 0401ef9dbr ; 2.484 ; g_XMTanEstCoefficients
	DD	0be482f23r			; -0.195492
	DD	0401de9e6r			; 2.4674
	DD	03ea2f983r			; 0.31831
;	COMDAT ?g_XMCosEstCoefficients@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMCosEstCoefficients@@3UXMVECTORF32@@B DD 03f800000r ; 1 ; g_XMCosEstCoefficients
	DD	0befd9e41r			; -0.495348
	DD	03d1eda81r			; 0.0387826
	DD	0ba72600cr			; -0.000924588
;	COMDAT ?g_XMSinEstCoefficients@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMSinEstCoefficients@@3UXMVECTORF32@@B DD 03f800000r ; 1 ; g_XMSinEstCoefficients
	DD	0be2a84b5r			; -0.166522
	DD	03c0658eer			; 0.00819991
	DD	0b92951der			; -0.000161476
;	COMDAT ?g_XMATanCoefficients2@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMATanCoefficients2@@3UXMVECTORF32@@B DD 03d70f0f1r ; 0.0588235 ; g_XMATanCoefficients2
	DD	03d579436r			; 0.0526316
	DD	03d430c31r			; 0.047619
	DD	03d321643r			; 0.0434783
;	COMDAT ?g_XMATanCoefficients1@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMATanCoefficients1@@3UXMVECTORF32@@B DD 03de38e39r ; 0.111111 ; g_XMATanCoefficients1
	DD	03dba2e8cr			; 0.0909091
	DD	03d9d89d9r			; 0.0769231
	DD	03d888889r			; 0.0666667
;	COMDAT ?g_XMATanCoefficients0@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMATanCoefficients0@@3UXMVECTORF32@@B DD 03f800000r ; 1 ; g_XMATanCoefficients0
	DD	03eaaaaabr			; 0.333333
	DD	03e4ccccdr			; 0.2
	DD	03e124925r			; 0.142857
;	COMDAT ?g_XMASinCoefficients2@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMASinCoefficients2@@3UXMVECTORF32@@B DD 0bfaf4418r ; -1.36927 ; g_XMASinCoefficients2
	DD	0c08f6ad9r			; -4.48179
	DD	03fb58485r			; 1.41811
	DD	040af6ad8r			; 5.48179
;	COMDAT ?g_XMASinCoefficients1@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMASinCoefficients1@@3UXMVECTORF32@@B DD 03f1dd7b6r ; 0.616573 ; g_XMASinCoefficients1
	DD	0408980bdr			; 4.29697
	DD	0bf983f2fr			; -1.18943
	DD	0c0d1360er			; -6.53785
;	COMDAT ?g_XMASinCoefficients0@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMASinCoefficients0@@3UXMVECTORF32@@B DD 0bd6dd42dr ; -0.0580637 ; g_XMASinCoefficients0
	DD	0bed65553r			; -0.41862
	DD	03e663246r			; 0.224801
	DD	0400b1889r			; 2.17337
;	COMDAT ?g_XMTanCoefficients2@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMTanCoefficients2@@3UXMVECTORF32@@B DD 03a1aac12r ; 0.000590027 ; g_XMTanCoefficients2
	DD	0397abeb9r			; 0.000239129
	DD	038cb3f0cr			; 9.69154e-005
	DD	03824bec9r			; 3.92783e-005
;	COMDAT ?g_XMTanCoefficients1@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMTanCoefficients1@@3UXMVECTORF32@@B DD 03cb327a4r ; 0.0218695 ; g_XMTanCoefficients1
	DD	03c11371br			; 0.00886324
	DD	03b6b69e9r			; 0.00359213
	DD	03abed1b3r			; 0.00145583
;	COMDAT ?g_XMTanCoefficients0@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMTanCoefficients0@@3UXMVECTORF32@@B DD 03f800000r ; 1 ; g_XMTanCoefficients0
	DD	03eaaaaabr			; 0.333333
	DD	03e088889r			; 0.133333
	DD	03d5d0dd1r			; 0.0539683
;	COMDAT ?g_XMCosCoefficients2@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMCosCoefficients2@@3UXMVECTORF32@@B DD 029573f9fr ; 4.77948e-014 ; g_XMCosCoefficients2
	DD	0a53413c3r			; -1.56192e-016
	DD	020f2a15dr			; 4.11032e-019
	DD	09c8671cbr			; -8.89679e-022
;	COMDAT ?g_XMCosCoefficients1@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMCosCoefficients1@@3UXMVECTORF32@@B DD 037d00d01r ; 2.48016e-005 ; g_XMCosCoefficients1
	DD	0b493f27er			; -2.75573e-007
	DD	0310f76c8r			; 2.08768e-009
	DD	0ad49cba5r			; -1.14707e-011
;	COMDAT ?g_XMCosCoefficients0@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMCosCoefficients0@@3UXMVECTORF32@@B DD 03f800000r ; 1 ; g_XMCosCoefficients0
	DD	0bf000000r			; -0.5
	DD	03d2aaaabr			; 0.0416667
	DD	0bab60b61r			; -0.00138889
;	COMDAT ?g_XMSinCoefficients2@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMSinCoefficients2@@3UXMVECTORF32@@B DD 0274a963cr ; 2.81146e-015 ; g_XMSinCoefficients2
	DD	0a317a4dar			; -8.22064e-018
	DD	01eb8dc78r			; 1.95729e-020
	DD	09a3b0da1r			; -3.86817e-023
;	COMDAT ?g_XMSinCoefficients1@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMSinCoefficients1@@3UXMVECTORF32@@B DD 03638ef1dr ; 2.75573e-006 ; g_XMSinCoefficients1
	DD	0b2d7322br			; -2.50521e-008
	DD	02f309231r			; 1.6059e-010
	DD	0ab573f9fr			; -7.64716e-013
;	COMDAT ?g_XMSinCoefficients0@@3UXMVECTORF32@@B
.rdata	SEGMENT
?g_XMSinCoefficients0@@3UXMVECTORF32@@B DD 03f800000r ; 1 ; g_XMSinCoefficients0
	DD	0be2aaaabr			; -0.166667
	DD	03c088889r			; 0.00833333
	DD	0b9500d01r			; -0.000198413
;	COMDAT D3DTESSPRIMITIVEVERTEXCOUNT
.rdata	SEGMENT
D3DTESSPRIMITIVEVERTEXCOUNT DD 00H
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	00H
	DD	01H
	DD	01H
	DD	03H
	DD	00H
	DD	01H
	DD	02H
	DD	01H
	DD	02H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	04H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	01H
	DD	00H
	DD	01H
	DD	00H
;	COMDAT D3DPRIMITIVEVERTEXCOUNT
.rdata	SEGMENT
D3DPRIMITIVEVERTEXCOUNT DD 00H
	DD	00H
	DD	01H
	DD	00H
	DD	02H
	DD	00H
	DD	01H
	DD	01H
	DD	03H
	DD	00H
	DD	01H
	DD	02H
	DD	01H
	DD	02H
	DD	00H
	DD	00H
	DD	03H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	04H
	DD	00H
;	COMDAT __C1_11886
.XBLD$W	SEGMENT
__C1_11886 DW	04331H
	DW	00H
	DW	00H
	DW	00H
	DW	010H
	DW	00H
	DW	02e6eH
	DW	04400H
;	COMDAT __C2_11886
.XBLD$W	SEGMENT
__C2_11886 DB	'C2', 00H, 00H, 00H, 00H, 00H, 00H, 00H, 010H, 00H, 00H, '.'
	DB	'nD', 00H
PUBLIC	?HvxSetState@@YAII@Z				; HvxSetState
; Function compile flags: /Odsu

	.code

?HvxSetState@@YAII@Z PROC NEAR				; HvxSetState, COMDAT

; Begin code for function: ?HvxSetState@@YAII@Z
; File c:\users\permanulled\desktop\trainer_engine\trainer engine\trainer\util.cpp
; Line 9
	li           r0,123		; 7Bh
; Line 10
	sc
; Line 11
	blr
; End code for function: ?HvxSetState@@YAII@Z
?HvxSetState@@YAII@Z ENDP
							; HvxSetState
PUBLIC	?GLPR_FUN@@YAXXZ				; GLPR_FUN
; Function compile flags: /Odsu

	.code

?GLPR_FUN@@YAXXZ PROC NEAR				; GLPR_FUN, COMDAT

; Begin code for function: ?GLPR_FUN@@YAXXZ
; Line 18
	std          r14,-98h(r1)
; Line 19
	std          r15,-90h(r1)
; Line 20
	std          r16,-88h(r1)
; Line 21
	std          r17,-80h(r1)
; Line 22
	std          r18,-78h(r1)
; Line 23
	std          r19,-70h(r1)
; Line 24
	std          r20,-68h(r1)
; Line 25
	std          r21,-60h(r1)
; Line 26
	std          r22,-58h(r1)
; Line 27
	std          r23,-50h(r1)
; Line 28
	std          r24,-48h(r1)
; Line 29
	std          r25,-40h(r1)
; Line 30
	std          r26,-38h(r1)
; Line 31
	std          r27,-30h(r1)
; Line 32
	std          r28,-28h(r1)
; Line 33
	std          r29,-20h(r1)
; Line 34
	std          r30,-18h(r1)
; Line 35
	std          r31,-10h(r1)
; Line 36
	stw          r12,-8(r1)
; Line 37
	blr
; End code for function: ?GLPR_FUN@@YAXXZ
?GLPR_FUN@@YAXXZ ENDP
							; GLPR_FUN
PUBLIC	?interpretBranchDest@@YAKKK@Z			; interpretBranchDest
; Function compile flags: /Ogsu

	.code

?interpretBranchDest@@YAKKK@Z PROC NEAR			; interpretBranchDest, COMDAT

; Begin code for function: ?interpretBranchDest@@YAKKK@Z
; Line 46
	rlwinm.      r9,r4,0,6,6
	rlwinm       r11,r4,0,6,29
	clrlwi       r10,r3,1
	beq          $LN1@interpretB
; Line 47
	oris         r11,r11,64512		; 0FC00h
$LN1@interpretB:
; Line 48
	add          r11,r10,r11
; Line 49
	clrrwi       r10,r3,31
	or           r3,r11,r10
; Line 50
	blr
; End code for function: ?interpretBranchDest@@YAKKK@Z
?interpretBranchDest@@YAKKK@Z ENDP
							; interpretBranchDest
PUBLIC	?findInterpretBranch@@YAKPAKK@Z			; findInterpretBranch
; Function compile flags: /Ogsu

	.code

?findInterpretBranch@@YAKPAKK@Z	PROC NEAR		; findInterpretBranch, COMDAT

; Begin code for function: ?findInterpretBranch@@YAKPAKK@Z
; Line 55
	li           r8,0
; Line 56
	li           r11,0
	cmplwi       cr6,r4,0
	beq          cr6,$LN2@findInterp
$LL4@findInterp:					; Start of loop
; Line 58
	slwi         r10,r11,2
	lis          r7,18432		; 4800h
	add          r10,r10,r3
	lwz          r9,0(r10)
	clrrwi       r6,r9,26
	cmplw        cr6,r6,r7
	bne          cr6,$LN3@findInterp
; Line 60
	rlwinm.      r8,r9,0,6,6
	rlwinm       r11,r9,0,6,29
	clrlwi       r9,r10,1
	beq          $LN7@findInterp
	oris         r11,r11,64512		; 0FC00h
$LN7@findInterp:
	add          r9,r9,r11
	clrrwi       r10,r10,31
; Line 61
	mr           r11,r4
	or           r8,r9,r10
$LN3@findInterp:
; Line 56
	addi         r11,r11,1
	cmplw        cr6,r11,r4
	blt          cr6,$LL4@findInterp
$LN2@findInterp:
; Line 64
	mr           r3,r8
; Line 65
	blr
; End code for function: ?findInterpretBranch@@YAKPAKK@Z
?findInterpretBranch@@YAKPAKK@Z ENDP
							; findInterpretBranch
PUBLIC	?relinkGPLR@@YAKHPAK0@Z				; relinkGPLR
; Function compile flags: /Ogsu

	.code

?relinkGPLR@@YAKHPAK0@Z	PROC NEAR			; relinkGPLR, COMDAT

; Begin code for function: ?relinkGPLR@@YAKHPAK0@Z
; Line 104
	lis          r11,?GLPR_FUN@@YAXXZ
; Line 135
	lis          r8,15712		; 3D60h
	addi         r11,r11,?GLPR_FUN@@YAXXZ
	mr           r9,r3
	li           r3,0
	lwz          r10,0(r11)
	andis.       r7,r10,15712		; 3D60h
	cmplw        cr6,r7,r8
	bne          cr6,$LN6@relinkGPLR
; Line 114
	lha          r11,6(r11)
	slwi         r10,r10,16
	add          r11,r11,r10
$LN6@relinkGPLR:
; Line 120
	rlwinm.      r10,r9,0,6,6
	beq          $LN5@relinkGPLR
; Line 121
	oris         r9,r9,64512		; 0FC00h
$LN5@relinkGPLR:
; Line 123
	srawi        r9,r9,2
	li           r10,20		; 14h
	addze        r9,r9
	slwi         r8,r9,2
	subf         r9,r4,r11
	mtctr        r10
	lwzx         r10,r8,r5
$LL4@relinkGPLR:					; Start of loop
; Line 127
	lwz          r8,0(r11)
	cmplw        cr6,r10,r8
	bne          cr6,$LN3@relinkGPLR
; Line 130
	rlwinm       r8,r9,0,6,29
	oris         r3,r8,18432		; 4800h
	ori          r3,r3,1
$LN3@relinkGPLR:
; Line 125
	addi         r11,r11,4
	addi         r9,r9,4
	bdnz         $LL4@relinkGPLR
; Line 136
	blr
; End code for function: ?relinkGPLR@@YAKHPAK0@Z
?relinkGPLR@@YAKHPAK0@Z ENDP
							; relinkGPLR
PUBLIC	?unhookFunctionStart@@YAXPAK0@Z			; unhookFunctionStart
; Function compile flags: /Ogsu

	.code

?unhookFunctionStart@@YAXPAK0@Z	PROC NEAR		; unhookFunctionStart, COMDAT

; Begin code for function: ?unhookFunctionStart@@YAXPAK0@Z
; Line 206
	cmplwi       cr6,r3,0
	beqlr        cr6
	cmplwi       cr6,r4,0
	beqlr        cr6
; Line 209
	li           r10,4
	mr           r11,r3
	subf         r9,r3,r4
	mtctr        r10
$LL6@unhookFunc:					; Start of loop
; Line 211
	lwzx         r10,r9,r11
	stw          r10,0(r11)
	addi         r11,r11,4
	bdnz         $LL6@unhookFunc
; Line 213
	dcbst        r0,r3
	sync
	isync
$LN1@unhookFunc:
; Line 215
	blr
; End code for function: ?unhookFunctionStart@@YAXPAK0@Z
?unhookFunctionStart@@YAXPAK0@Z ENDP
							; unhookFunctionStart
PUBLIC	?patchInJump@@YAXPAKKH@Z			; patchInJump
; Function compile flags: /Ogsu

	.code
temp$ = -16						; size = 16

?patchInJump@@YAXPAKKH@Z PROC NEAR			; patchInJump, COMDAT

; Begin code for function: ?patchInJump@@YAXPAKKH@Z
; Line 224
	rlwinm.      r11,r4,0,16,16
; Line 225
	srwi         r11,r4,16
	beq          $LN4@patchInJum
	addis        r11,r11,15712		; 3D60h
	addi         r11,r11,1
; Line 226
	b            $LN7@patchInJum
$LN4@patchInJum:
; Line 227
	addis        r11,r11,15712		; 3D60h
$LN7@patchInJum:
	stw          r11,temp$(r1)		; 4294967280 (0FFFFFFF0h)
; Line 229
	clrlwi       r11,r4,16
	lis          r10,32105		; 7D69h
; Line 230
	addis        r11,r11,14699		; 396Bh
	ori          r10,r10,934		; 3A6h
; Line 232
	stw          r11,temp$+4(r1)		; 4294967284 (0FFFFFFF4h)
	cmpwi        cr6,r5,0
	stw          r10,temp$+8(r1)		; 4294967288 (0FFFFFFF8h)
; Line 233
	lis          r11,20096		; 4E80h
	beq          cr6,$LN2@patchInJum
	ori          r11,r11,1057		; 421h
; Line 234
	b            $LN8@patchInJum
$LN2@patchInJum:
; Line 229
	ori          r11,r11,1056		; 420h
$LN8@patchInJum:
; Line 235
	stw          r11,temp$+0Ch(r1)		; 4294967292 (0FFFFFFFCh)
; Line 238
	addi         r11,r1,temp$
	lwz          r10,0(r11)
	lwz          r9,4(r11)
	lwz          r8,8(r11)
	lwz          r11,0Ch(r11)
	stw          r10,0(r3)
	stw          r9,4(r3)
	stw          r8,8(r3)
	stw          r11,0Ch(r3)
; Line 239
	blr
; End code for function: ?patchInJump@@YAXPAKKH@Z
?patchInJump@@YAXPAKKH@Z ENDP
							; patchInJump
PUBLIC	?makeBranch@@YAKKKH@Z				; makeBranch
; Function compile flags: /Ogsu

	.code

?makeBranch@@YAKKKH@Z PROC NEAR				; makeBranch, COMDAT

; Begin code for function: ?makeBranch@@YAKKKH@Z
; Line 244
	subf         r11,r3,r4
	clrlwi       r11,r11,6
	or           r11,r11,r5
	oris         r3,r11,18432		; 4800h
; Line 245
	blr
; End code for function: ?makeBranch@@YAKKKH@Z
?makeBranch@@YAKKKH@Z ENDP
							; makeBranch
PUBLIC	?swap_endian@@YAXPAEK@Z				; swap_endian
EXTRN	??_V@YAXPAX@Z:PROC				; operator delete[]
EXTRN	??_U@YAPAXI@Z:PROC				; operator new[]
EXTRN	__restgprlr_29:PROC
EXTRN	__savegprlr_29:PROC
EXTRN	memcpy:PROC
;	COMDAT .pdata
.pdata	SEGMENT
$T87021	DD	?swap_endian@@YAXPAEK@Z
	DD	040001a03H
; Function compile flags: /Ogsu

	.code

?swap_endian@@YAXPAEK@Z	PROC NEAR			; swap_endian, COMDAT

; Begin code for function: ?swap_endian@@YAXPAEK@Z
; Line 249
	mflr         r12
	bl           __savegprlr_29
	stwu         r1,-70h(r1)
.endprolog
$M87019:
	mr           r29,r3
; Line 251
	mr           r3,r4
	mr           r30,r4
	bl           ??_U@YAPAXI@Z
; Line 252
	addic.       r11,r30,-4		; 0FFFCh
	mr           r31,r3
	blt          $LN1@swap_endia
; Line 251
	addi         r9,r11,4
	addi         r10,r3,-4		; 0FFFCh
	srwi         r9,r9,2
	mtctr        r9
$LL3@swap_endia:					; Start of loop
; Line 253
	lbzx         r9,r11,r29
	addi         r11,r11,-4		; 0FFFCh
	stwu         r9,4(r10)
	bdnz         $LL3@swap_endia
$LN1@swap_endia:
; Line 255
	mr           r5,r30
	mr           r4,r31
	mr           r3,r29
	bl           memcpy
; Line 256
	mr           r3,r31
	bl           ??_V@YAXPAX@Z
; Line 257
	addi         r1,r1,112		; 70h
	b            __restgprlr_29
$M87020:
; End code for function: ?swap_endian@@YAXPAEK@Z
?swap_endian@@YAXPAEK@Z ENDP
							; swap_endian
PUBLIC	?hookFunctionStart@@YAXPAK00K@Z			; hookFunctionStart
EXTRN	__restgprlr_28:PROC
EXTRN	__savegprlr_28:PROC
;	COMDAT .pdata
.pdata	SEGMENT
$T87034	DD	?hookFunctionStart@@YAXPAK00K@Z
	DD	040005003H
; Function compile flags: /Ogsu

	.code
temp$ = 80						; size = 64
addrtemp$ = 144						; size = 64

?hookFunctionStart@@YAXPAK00K@Z	PROC NEAR		; hookFunctionStart, COMDAT

; Begin code for function: ?hookFunctionStart@@YAXPAK00K@Z
; Line 143
	mflr         r12
	bl           __savegprlr_28
	stwu         r1,-100h(r1)
.endprolog
$M87032:
	mr           r30,r3
	mr           r29,r4
	mr           r31,r5
; Line 147
	addi         r3,r1,addrtemp$
	li           r5,64		; 40h
	mr           r4,r30
	mr           r28,r6
	bl           memcpy
; Line 150
	cmplwi       cr6,r29,0
	beq          cr6,$LN12@hookFuncti
; Line 153
	addi         r11,r30,16		; 10h
; Line 157
	rlwinm.      r10,r11,0,16,16
; Line 159
	srwi         r10,r11,16
	beq          $LN11@hookFuncti
	addis        r10,r10,15712		; 3D60h
	addi         r10,r10,1
; Line 160
	b            $LN19@hookFuncti
$LN11@hookFuncti:
; Line 162
	addis        r10,r10,15712		; 3D60h
$LN19@hookFuncti:
	stw          r10,temp$(r1)		; 80 (50h)
; Line 166
	clrlwi       r11,r11,16
; Line 189
	lis          r10,32105		; 7D69h
	addis        r11,r11,14699		; 396Bh
	ori          r10,r10,934		; 3A6h
	cmplwi       cr6,r31,0
	stw          r11,temp$+4(r1)		; 84 (54h)
	stw          r10,temp$+8(r1)		; 88 (58h)
	beq          cr6,$LN8@hookFuncti
; Line 173
	addi         r11,r1,addrtemp$
	lwz          r10,0(r11)
	lwz          r9,4(r11)
	lwz          r8,8(r11)
	lwz          r11,0Ch(r11)
	stw          r10,0(r31)
	stw          r9,4(r31)
	stw          r8,8(r31)
	stw          r11,0Ch(r31)
$LN8@hookFuncti:
; Line 185
	addi         r11,r1,addrtemp$
	addi         r4,r29,12		; 0Ch
	subf         r31,r11,r30
	li           r6,0
$LL5@hookFuncti:					; Start of loop
; Line 189
	addi         r11,r1,addrtemp$
	lis          r12,18432		; 4800h
	add          r10,r6,r11
	lis          r9,18432		; 4800h
	ori          r12,r12,3
	lwzx         r11,r6,r11
	ori          r9,r9,1
	and          r8,r11,r12
	cmplw        cr6,r8,r9
	bne          cr6,$LN2@hookFuncti
; Line 180
	lis          r12,-18433		; 0B7FFh
	add          r5,r31,r10
	ori          r12,r12,65532		; 0FFFCh
	and          r3,r11,r12
	bl           ?relinkGPLR@@YAKHPAK0@Z
	addi         r11,r1,temp$+0Ch
	stwx         r3,r6,r11
; Line 182
	b            $LN4@hookFuncti
$LN2@hookFuncti:
; Line 185
	addi         r10,r1,temp$+0Ch
	stwx         r11,r6,r10
$LN4@hookFuncti:
	addi         r6,r6,4
	addi         r4,r4,4
	cmpwi        cr6,r6,16		; 10h
	blt          cr6,$LL5@hookFuncti
; Line 189
	lis          r11,20096		; 4E80h
; Line 198
	addi         r4,r1,temp$
	ori          r11,r11,1056		; 420h
	li           r5,32		; 20h
	stw          r11,temp$+1Ch(r1)		; 108 (6Ch)
	mr           r3,r29
	bl           memcpy
; Line 200
	li           r5,0
	mr           r4,r28
	mr           r3,r30
	bl           ?patchInJump@@YAXPAKKH@Z
$LN12@hookFuncti:
; Line 202
	addi         r1,r1,256		; 100h
	b            __restgprlr_28
$M87033:
; End code for function: ?hookFunctionStart@@YAXPAK00K@Z
?hookFunctionStart@@YAXPAK00K@Z ENDP
							; hookFunctionStart
END
